//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PowerToys.Run.Plugin.TimeDate.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PowerToys.Run.Plugin.TimeDate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to copy result to the clipboard.
        /// </summary>
        internal static string Microsoft_plugin_timedate_copyToClipboard {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_copyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Microsoft_plugin_timedate_date {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now (Date and time).
        /// </summary>
        internal static string Microsoft_plugin_timedate_now {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide actual time and date informations.
        /// </summary>
        internal static string Microsoft_plugin_timedate_plugin_description {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time and Date.
        /// </summary>
        internal static string Microsoft_plugin_timedate_plugin_name {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only date, time and now result in global results.
        /// </summary>
        internal static string Microsoft_plugin_timedate_settingDateTimeGlobalOnly {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_settingDateTimeGlobalOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show date with weekday.
        /// </summary>
        internal static string Microsoft_plugin_timedate_settingDateWithWeekday {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_settingDateWithWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show time with seconds.
        /// </summary>
        internal static string Microsoft_plugin_timedate_settingTimeWithSeconds {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_settingTimeWithSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Microsoft_plugin_timedate_time {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time as Unix Timestamp.
        /// </summary>
        internal static string Microsoft_plugin_timedate_timeUnix {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_timeUnix", resourceCulture);
            }
        }
    }
}
