//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageResizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageResizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Advanced_About {
            get {
                return ResourceManager.GetString("Advanced_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new size.
        /// </summary>
        public static string Advanced_CreateSize {
            get {
                return ResourceManager.GetString("Advanced_CreateSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Advanced_DeleteSize {
            get {
                return ResourceManager.GetString("Advanced_DeleteSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        public static string Advanced_Encoding {
            get {
                return ResourceManager.GetString("Advanced_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Fallback encoder:.
        /// </summary>
        public static string Advanced_FallbackEncoder {
            get {
                return ResourceManager.GetString("Advanced_FallbackEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Advanced_File {
            get {
                return ResourceManager.GetString("Advanced_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Filename:.
        /// </summary>
        public static string Advanced_FileName {
            get {
                return ResourceManager.GetString("Advanced_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original filename.
        /// </summary>
        public static string Advanced_FileNameToken1 {
            get {
                return ResourceManager.GetString("Advanced_FileNameToken1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size name.
        /// </summary>
        public static string Advanced_FileNameToken2 {
            get {
                return ResourceManager.GetString("Advanced_FileNameToken2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected width.
        /// </summary>
        public static string Advanced_FileNameToken3 {
            get {
                return ResourceManager.GetString("Advanced_FileNameToken3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected height.
        /// </summary>
        public static string Advanced_FileNameToken4 {
            get {
                return ResourceManager.GetString("Advanced_FileNameToken4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual width (pixels).
        /// </summary>
        public static string Advanced_FileNameToken5 {
            get {
                return ResourceManager.GetString("Advanced_FileNameToken5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual height (pixels).
        /// </summary>
        public static string Advanced_FileNameToken6 {
            get {
                return ResourceManager.GetString("Advanced_FileNameToken6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following parameters can be used..
        /// </summary>
        public static string Advanced_FileNameTokens {
            get {
                return ResourceManager.GetString("Advanced_FileNameTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _JPEG quality level:.
        /// </summary>
        public static string Advanced_JpegQualityLevel {
            get {
                return ResourceManager.GetString("Advanced_JpegQualityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Use original date modified.
        /// </summary>
        public static string Advanced_KeepDateModified {
            get {
                return ResourceManager.GetString("Advanced_KeepDateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _PNG interlacing:.
        /// </summary>
        public static string Advanced_PngInterlaceOption {
            get {
                return ResourceManager.GetString("Advanced_PngInterlaceOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizes.
        /// </summary>
        public static string Advanced_Sizes {
            get {
                return ResourceManager.GetString("Advanced_Sizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TIFF compression:.
        /// </summary>
        public static string Advanced_TiffCompressOption {
            get {
                return ResourceManager.GetString("Advanced_TiffCompressOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Options.
        /// </summary>
        public static string Advanced_Title {
            get {
                return ResourceManager.GetString("Advanced_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string AllFilesFilter {
            get {
                return ResourceManager.GetString("AllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2019 Brice Lambson. All rights reserved..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Resizer for Windows.
        /// </summary>
        public static string ImageResizer {
            get {
                return ResourceManager.GetString("ImageResizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (auto).
        /// </summary>
        public static string Input_Auto {
            get {
                return ResourceManager.GetString("Input_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Select a size..
        /// </summary>
        public static string Input_Content {
            get {
                return ResourceManager.GetString("Input_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Input_Custom {
            get {
                return ResourceManager.GetString("Input_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ign_ore the orientation of pictures.
        /// </summary>
        public static string Input_IgnoreOrientation {
            get {
                return ResourceManager.GetString("Input_IgnoreOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize your pictures.
        /// </summary>
        public static string Input_MainInstruction {
            get {
                return ResourceManager.GetString("Input_MainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R_esize the original pictures (don&apos;t create copies).
        /// </summary>
        public static string Input_Replace {
            get {
                return ResourceManager.GetString("Input_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Resize.
        /// </summary>
        public static string Input_Resize {
            get {
                return ResourceManager.GetString("Input_Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced options....
        /// </summary>
        public static string Input_ShowAdvanced {
            get {
                return ResourceManager.GetString("Input_ShowAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Make pictures smaller but not larger.
        /// </summary>
        public static string Input_ShrinkOnly {
            get {
                return ResourceManager.GetString("Input_ShrinkOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Picture Files.
        /// </summary>
        public static string PictureFilter {
            get {
                return ResourceManager.GetString("PictureFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Default).
        /// </summary>
        public static string PngInterlaceOption_Default {
            get {
                return ResourceManager.GetString("PngInterlaceOption_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string PngInterlaceOption_Off {
            get {
                return ResourceManager.GetString("PngInterlaceOption_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string PngInterlaceOption_On {
            get {
                return ResourceManager.GetString("PngInterlaceOption_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizing your pictures....
        /// </summary>
        public static string Progress_MainInstruction {
            get {
                return ResourceManager.GetString("Progress_MainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Stop.
        /// </summary>
        public static string Progress_Stop {
            get {
                return ResourceManager.GetString("Progress_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0} hour, {1} minute remaining..
        /// </summary>
        public static string Progress_TimeRemaining_HourMinute {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_HourMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0} hour, {1} minutes remaining..
        /// </summary>
        public static string Progress_TimeRemaining_HourMinutes {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_HourMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0} hours, {1} minute remaining..
        /// </summary>
        public static string Progress_TimeRemaining_HoursMinute {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_HoursMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0} hours, {1} minutes remaining..
        /// </summary>
        public static string Progress_TimeRemaining_HoursMinutes {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_HoursMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {1} minute, {2} second remaining..
        /// </summary>
        public static string Progress_TimeRemaining_MinuteSecond {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_MinuteSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {1} minute, {2} seconds remaining..
        /// </summary>
        public static string Progress_TimeRemaining_MinuteSeconds {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_MinuteSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {1} minutes, {2} second remaining..
        /// </summary>
        public static string Progress_TimeRemaining_MinutesSecond {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_MinutesSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {1} minutes, {2} seconds remaining..
        /// </summary>
        public static string Progress_TimeRemaining_MinutesSeconds {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_MinutesSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {2} second remaining..
        /// </summary>
        public static string Progress_TimeRemaining_Second {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {2} seconds remaining..
        /// </summary>
        public static string Progress_TimeRemaining_Seconds {
            get {
                return ResourceManager.GetString("Progress_TimeRemaining_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string ResizeFit_Fill {
            get {
                return ResourceManager.GetString("ResizeFit_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fills.
        /// </summary>
        public static string ResizeFit_Fill_ThirdPersonSingular {
            get {
                return ResourceManager.GetString("ResizeFit_Fill_ThirdPersonSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit.
        /// </summary>
        public static string ResizeFit_Fit {
            get {
                return ResourceManager.GetString("ResizeFit_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fits within.
        /// </summary>
        public static string ResizeFit_Fit_ThirdPersonSingular {
            get {
                return ResourceManager.GetString("ResizeFit_Fit_ThirdPersonSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        public static string ResizeFit_Stretch {
            get {
                return ResourceManager.GetString("ResizeFit_Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stretches to.
        /// </summary>
        public static string ResizeFit_Stretch_ThirdPersonSingular {
            get {
                return ResourceManager.GetString("ResizeFit_Stretch_ThirdPersonSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeters.
        /// </summary>
        public static string ResizeUnit_Centimeter {
            get {
                return ResourceManager.GetString("ResizeUnit_Centimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches.
        /// </summary>
        public static string ResizeUnit_Inch {
            get {
                return ResourceManager.GetString("ResizeUnit_Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string ResizeUnit_Percent {
            get {
                return ResourceManager.GetString("ResizeUnit_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixels.
        /// </summary>
        public static string ResizeUnit_Pixel {
            get {
                return ResourceManager.GetString("ResizeUnit_Pixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Results_Close {
            get {
                return ResourceManager.GetString("Results_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t resize the following pictures.
        /// </summary>
        public static string Results_MainInstruction {
            get {
                return ResourceManager.GetString("Results_MainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCITT3.
        /// </summary>
        public static string TiffCompressOption_Ccitt3 {
            get {
                return ResourceManager.GetString("TiffCompressOption_Ccitt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCITT4.
        /// </summary>
        public static string TiffCompressOption_Ccitt4 {
            get {
                return ResourceManager.GetString("TiffCompressOption_Ccitt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Default).
        /// </summary>
        public static string TiffCompressOption_Default {
            get {
                return ResourceManager.GetString("TiffCompressOption_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LZW.
        /// </summary>
        public static string TiffCompressOption_Lzw {
            get {
                return ResourceManager.GetString("TiffCompressOption_Lzw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string TiffCompressOption_None {
            get {
                return ResourceManager.GetString("TiffCompressOption_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RLE.
        /// </summary>
        public static string TiffCompressOption_Rle {
            get {
                return ResourceManager.GetString("TiffCompressOption_Rle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string TiffCompressOption_Zip {
            get {
                return ResourceManager.GetString("TiffCompressOption_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be between &apos;{0}&apos; and &apos;{1}&apos;..
        /// </summary>
        public static string ValueMustBeBetween {
            get {
                return ResourceManager.GetString("ValueMustBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
