//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Plugin.Indexer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Plugin.Indexer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Disable non-indexed files warning 的本地化字符串。
        /// </summary>
        public static string disable_drive_detection_warning {
            get {
                return ResourceManager.GetString("disable_drive_detection_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excluded patterns 的本地化字符串。
        /// </summary>
        public static string excluded_patterns {
            get {
                return ResourceManager.GetString("excluded_patterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to set text in clipboard 的本地化字符串。
        /// </summary>
        public static string Microsoft_plugin_indexer_clipboard_failed {
            get {
                return ResourceManager.GetString("Microsoft_plugin_indexer_clipboard_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy path (Ctrl+C) 的本地化字符串。
        /// </summary>
        public static string Microsoft_plugin_indexer_copy_path {
            get {
                return ResourceManager.GetString("Microsoft_plugin_indexer_copy_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to go to Windows Search settings to fix. 的本地化字符串。
        /// </summary>
        public static string Microsoft_plugin_indexer_disable_warning_in_settings {
            get {
                return ResourceManager.GetString("Microsoft_plugin_indexer_disable_warning_in_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: Not all files are indexed. 的本地化字符串。
        /// </summary>
        public static string Microsoft_plugin_indexer_drivedetectionwarning {
            get {
                return ResourceManager.GetString("Microsoft_plugin_indexer_drivedetectionwarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t open this file 的本地化字符串。
        /// </summary>
        public static string Microsoft_plugin_indexer_file_open_failed {
            get {
                return ResourceManager.GetString("Microsoft_plugin_indexer_file_open_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to open folder at 的本地化字符串。
        /// </summary>
        public static string Microsoft_plugin_indexer_folder_open_failed {
            get {
                return ResourceManager.GetString("Microsoft_plugin_indexer_folder_open_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Microsoft_plugin_indexer_name {
            get {
                return ResourceManager.GetString("Microsoft_plugin_indexer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open containing folder (Ctrl+Shift+E) 的本地化字符串。
        /// </summary>
        public static string Microsoft_plugin_indexer_open_containing_folder {
            get {
                return ResourceManager.GetString("Microsoft_plugin_indexer_open_containing_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open path in console (Ctrl+Shift+C) 的本地化字符串。
        /// </summary>
        public static string Microsoft_plugin_indexer_open_in_console {
            get {
                return ResourceManager.GetString("Microsoft_plugin_indexer_open_in_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        public static string Microsoft_plugin_indexer_path {
            get {
                return ResourceManager.GetString("Microsoft_plugin_indexer_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searches files and folders. 的本地化字符串。
        /// </summary>
        public static string Microsoft_plugin_indexer_plugin_description {
            get {
                return ResourceManager.GetString("Microsoft_plugin_indexer_plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Search 的本地化字符串。
        /// </summary>
        public static string Microsoft_plugin_indexer_plugin_name {
            get {
                return ResourceManager.GetString("Microsoft_plugin_indexer_plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run as administrator (Ctrl+Shift+Enter) 的本地化字符串。
        /// </summary>
        public static string Microsoft_plugin_indexer_run_as_administrator {
            get {
                return ResourceManager.GetString("Microsoft_plugin_indexer_run_as_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run as different user (Ctrl+Shift+U) 的本地化字符串。
        /// </summary>
        public static string Microsoft_plugin_indexer_run_as_user {
            get {
                return ResourceManager.GetString("Microsoft_plugin_indexer_run_as_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Microsoft_plugin_indexer_subtitle_header {
            get {
                return ResourceManager.GetString("Microsoft_plugin_indexer_subtitle_header", resourceCulture);
            }
        }
    }
}
