//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CmdPal.Ext.WinGet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CmdPal.Ext.WinGet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string winget_author {
            get {
                return ResourceManager.GetString("winget_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string winget_copyright {
            get {
                return ResourceManager.GetString("winget_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0}. Are you connected to the internet?.
        /// </summary>
        public static string winget_create_catalog_error {
            get {
                return ResourceManager.GetString("winget_create_catalog_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinGet.
        /// </summary>
        public static string winget_display_name {
            get {
                return ResourceManager.GetString("winget_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading. {0} of {1}.
        /// </summary>
        public static string winget_download_progress {
            get {
                return ResourceManager.GetString("winget_download_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string winget_downloading {
            get {
                return ResourceManager.GetString("winget_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Extensions.
        /// </summary>
        public static string winget_install_extensions_name {
            get {
                return ResourceManager.GetString("winget_install_extensions_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for extensions on WinGet.
        /// </summary>
        public static string winget_install_extensions_subtitle {
            get {
                return ResourceManager.GetString("winget_install_extensions_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Command Palette extensions.
        /// </summary>
        public static string winget_install_extensions_title {
            get {
                return ResourceManager.GetString("winget_install_extensions_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished install.
        /// </summary>
        public static string winget_install_finished {
            get {
                return ResourceManager.GetString("winget_install_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string winget_install_name {
            get {
                return ResourceManager.GetString("winget_install_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished install for {0}.
        /// </summary>
        public static string winget_install_package_finished {
            get {
                return ResourceManager.GetString("winget_install_package_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing install for {0}....
        /// </summary>
        public static string winget_install_package_finishing {
            get {
                return ResourceManager.GetString("winget_install_package_finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing {0}....
        /// </summary>
        public static string winget_installing_package {
            get {
                return ResourceManager.GetString("winget_installing_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string winget_license {
            get {
                return ResourceManager.GetString("winget_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No packages found.
        /// </summary>
        public static string winget_no_packages_found {
            get {
                return ResourceManager.GetString("winget_no_packages_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search WinGet.
        /// </summary>
        public static string winget_page_name {
            get {
                return ResourceManager.GetString("winget_page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start typing to search for packages.
        /// </summary>
        public static string winget_placeholder_text {
            get {
                return ResourceManager.GetString("winget_placeholder_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string winget_publisher {
            get {
                return ResourceManager.GetString("winget_publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher Support.
        /// </summary>
        public static string winget_publisher_support {
            get {
                return ResourceManager.GetString("winget_publisher_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued {0} for download....
        /// </summary>
        public static string winget_queued_package_download {
            get {
                return ResourceManager.GetString("winget_queued_package_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued {0} for uninstall....
        /// </summary>
        public static string winget_queued_package_uninstall {
            get {
                return ResourceManager.GetString("winget_queued_package_uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes.
        /// </summary>
        public static string winget_release_notes {
            get {
                return ResourceManager.GetString("winget_release_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for extensions in the Store.
        /// </summary>
        public static string winget_search_store_title {
            get {
                return ResourceManager.GetString("winget_search_store_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error: {0}.
        /// </summary>
        public static string winget_unexpected_error {
            get {
                return ResourceManager.GetString("winget_unexpected_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished uninstall..
        /// </summary>
        public static string winget_uninstall_finished {
            get {
                return ResourceManager.GetString("winget_uninstall_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string winget_uninstall_name {
            get {
                return ResourceManager.GetString("winget_uninstall_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished uninstall for {0}.
        /// </summary>
        public static string winget_uninstall_package_finished {
            get {
                return ResourceManager.GetString("winget_uninstall_package_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing uninstall for {0}....
        /// </summary>
        public static string winget_uninstall_package_finishing {
            get {
                return ResourceManager.GetString("winget_uninstall_package_finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling {0}....
        /// </summary>
        public static string winget_uninstalling_package {
            get {
                return ResourceManager.GetString("winget_uninstalling_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View online.
        /// </summary>
        public static string winget_view_online {
            get {
                return ResourceManager.GetString("winget_view_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Release Notes.
        /// </summary>
        public static string winget_view_release_notes {
            get {
                return ResourceManager.GetString("winget_view_release_notes", resourceCulture);
            }
        }
    }
}
