PackageName: AgileBits.1Password
Name: 1Password
WindowFilter: "1Password.exe"
BackgroundProcess: false
Shortcuts:
  - SectionName: Basics
    Properties:
      - Name: View keyboard shortcuts
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - "/"
      - Name: Show Quick Access
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - "<Space>"
      - Name: Lock 1Password
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - L
  - SectionName: Navigation
    Properties:
      - Name: Find
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - F
      - Name: Switch to all accounts
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "<1>"
      - Name: "Switch accounts & collections"
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - '2 - 9'
      - Name: Back
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - "<Left>"
      - Name: Forward
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - "<Right>"
      - Name: Focus next row
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - "<Down>"
      - Name: Focus previous row
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - "<Up>"
      - Name: Focus right section
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - "<Right>"
      - Name: Focus left section
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - "<Left>"
  - SectionName: Selected item
    Properties:
      - Name: Copy primary field
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - C
      - Name: Copy password
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - C
      - Name: Copy one-time password
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - C
      - Name: "Open & fill in web browser"
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - F
      - Name: Open item in new window
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - O
      - Name: Edit item
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - E
      - Name: Save item
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - S
      - Name: Reveal concealed fields
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - R
      - Name: Archive item
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - "<Delete>"
      - Name: Delete item
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "<Delete>"
  - SectionName: View
    Properties:
      - Name: Show/hide sidebar
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - D
      - Name: Zoom in
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "+"
      - Name: Zoom out
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "-"
      - Name: Actual size
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "<0>"
