PackageName: Discord.Discord
Name: Discord
WindowFilter: "discord.exe"
BackgroundProcess: false
Shortcuts:
  - SectionName: Server and channel navigation
    Properties:
      - Name: Navigate between servers (up)
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - "<Up>"
      - Name: Navigate between servers (down)
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - "<Down>"
      - Name: Navigate between channels (up)
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - "<Up>"
      - Name: Navigate between channels (down)
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - "<Down>"
      - Name: Navigate between unread channels (up)
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: true
          Alt: true
          Keys:
            - "<Up>"
      - Name: Navigate between unread channels (down)
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: true
          Alt: true
          Keys:
            - "<Down>"
      - Name: Navigate between unread channels with mentions (up)
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: true
          Keys:
            - "<Up>"
      - Name: Navigate between unread channels with mentions (down)
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: true
          Keys:
            - "<Down>"
      - Name: Return to previous text channel
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - B
      - Name: Return to active audio channel
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - A
      - Name: Find or start a direct message
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - K
      - Name: Create or join a server
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - N
      - Name: Create a private group
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - T
  - SectionName: Message reading
    Properties:
      - Name: Mark channel as read
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - "<Escape>"
      - Name: Mark server as read
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: true
          Alt: false
          Keys:
            - "<Escape>"
      - Name: Scroll chat up a screen
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - PageUp
      - Name: Scroll chat down a screen
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - PageDown
      - Name: Jump to oldest unread message
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: true
          Alt: false
          Keys:
            - PageUp
  - SectionName: Pop-outs and panels
    Properties:
      - Name: Toggle pins pop-out
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - P
      - Name: Toggle mentions pop-out
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - I
      - Name: Toggle channel member list
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - U
      - Name: Toggle emoji picker
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - E
      - Name: Toggle hotkeys reference
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Slash
  - SectionName: Voice and calls
    Properties:
      - Name: Answer incoming call
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "<Enter>"
      - Name: Decline incoming call
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - "<Escape>"
      - Name: Start call in private message or group
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - LeftBracket
      - Name: Toggle mute
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - M
      - Name: Toggle deafen
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - D
  - SectionName: Other
    Properties:
      - Name: Focus text area
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - Tab
      - Name: Get help
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - H
      - Name: Upload a file
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - U
