PackageName: Microsoft.OneNote
Name: OneNote
WindowFilter: "onenote.exe"
BackgroundProcess: false
Shortcuts:
  - SectionName: Frequently used
    Properties:
      - Name: Open notebook
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - O
      - Name: Open a new OneNote window
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - M
      - Name: Create a Quick Note
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - M
      - Name: Dock the OneNote window
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - D
      - Name: Undo
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Z
      - Name: Redo
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Y
      - Name: Select all on page
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - A
      - Name: Cut
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - X
      - Name: Copy
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - C
      - Name: Paste
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - V
      - Name: Paste text only
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - V
      - Name: Check spelling
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - F7
      - Name: Print current page
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - P
  - SectionName: Format
    Properties:
      - Name: Bold
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - B
      - Name: Italic
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - I
      - Name: Underline
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - U
      - Name: Strikethrough
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - Minus
      - Name: Superscript
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - Plus
      - Name: Subscript
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - Minus
      - Name: Highlight selected text
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - H
      - Name: Insert hyperlink
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - K
      - Name: Bulleted list
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "."
      - Name: Numbered list
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "/"
      - Name: Apply Heading 1
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - "1"
      - Name: Apply Heading 2
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - "2"
      - Name: Apply Heading 3
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - "3"
      - Name: Clear all formatting
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - N
      - Name: Align left
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - L
      - Name: Align right
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - R
      - Name: Copy formatting
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - C
      - Name: Paste formatting
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - V
  - SectionName: Insert
    Properties:
      - Name: Insert current date
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: true
          Alt: true
          Keys:
            - D
      - Name: Insert current time
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: true
          Alt: true
          Keys:
            - T
      - Name: Insert current date and time
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: true
          Alt: true
          Keys:
            - F
      - Name: Start math equation
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - "="
      - Name: Insert line break
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: true
          Alt: false
          Keys:
            - "<Enter>"
  - SectionName: Tags
    Properties:
      - Name: To Do tag
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "1"
      - Name: Important tag
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "2"
      - Name: Question tag
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "3"
      - Name: Remember for later tag
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "4"
      - Name: Definition tag
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "5"
      - Name: Remove all note tags
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "0"
  - SectionName: Pages and sections
    Properties:
      - Name: Add a new page
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - N
      - Name: Create a new section
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - T
      - Name: Go to next section
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Tab
      - Name: Go to previous section
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - Tab
      - Name: Next page in section
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - PageDown
      - Name: Previous page in section
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - PageUp
      - Name: First page in section
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - Home
      - Name: Last page in section
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - End
      - Name: Enable or disable full page view
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - F11
      - Name: Zoom in
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Plus
      - Name: Zoom out
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Minus
  - SectionName: Search
    Properties:
      - Name: Search all notebooks
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - E
      - Name: Search current page
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - F
