PackageName: Microsoft.Paint
Name: Paint
WindowFilter: "mspaint.exe"
BackgroundProcess: false
Shortcuts:
  - SectionName: File
    Properties:
      - Name: New picture
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - N
      - Name: Open
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - O
      - Name: Save
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - S
      - Name: Save as
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - S
      - Name: Print
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - P
  - SectionName: Edit
    Properties:
      - Name: Undo
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Z
      - Name: Redo
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Y
      - Name: Cut
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - X
      - Name: Copy
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - C
      - Name: Paste
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - V
      - Name: Select all
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - A
      - Name: Delete selection
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - Delete
      - Name: Move selection
        Description: Use the arrow keys to nudge the current selection one pixel.
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - "<Arrow>"
  - SectionName: View
    Properties:
      - Name: Zoom in
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - PageUp
      - Name: Zoom out
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - PageDown
      - Name: Show or hide gridlines
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - G
      - Name: Show or hide rulers
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - R
      - Name: Full screen
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - F11
  - SectionName: Image
    Properties:
      - Name: Image properties
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - E
      - Name: Resize and skew
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - W
      - Name: Crop to selection
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - X
      - Name: Invert colors
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - I
  - SectionName: Tools
    Properties:
      - Name: Increase brush or tool width
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Plus
      - Name: Decrease brush or tool width
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Minus
      - Name: Text tool
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - T
  - SectionName: Text tool
    Properties:
      - Name: Bold
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - B
      - Name: Italic
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - I
      - Name: Underline
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - U
