PackageName: Microsoft.Edge
Name: Microsoft Edge
WindowFilter: "msedge.exe"
BackgroundProcess: false
Shortcuts:
  - SectionName: Tabs and windows
    Properties:
      - Name: New tab
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - T
      - Name: Reopen the last closed tab
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - T
      - Name: Switch to the next tab
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Tab
      - Name: Switch to the previous tab
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - Tab
      - Name: Switch to a specific tab
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - 1
      - Name: Switch to the last tab
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - 9
      - Name: Close the current tab
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - W
      - Name: Close the current tab (alt)
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - F4
      - Name: Close the current window
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - W
      - Name: Close the current window (alt)
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - F4
      - Name: New window
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - N
      - Name: New InPrivate window
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - N
      - Name: Duplicate the current tab
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - K
      - Name: Mute the current tab
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - M
      - Name: Switch to the next tab (alt)
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - PageDown
      - Name: Switch to the previous tab (alt)
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - PageUp
      - Name: Enter full screen
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - F11
  - SectionName: Address bar
    Properties:
      - Name: Select the URL in the address bar
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - L
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - D
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - F4
      - Name: Open a search query in the address bar
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - E
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - K
      - Name: Add www. and .com to text in the address bar
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "<Enter>"
      - Name: Paste and search or paste and go
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - L
  - SectionName: Browser features
    Properties:
      - Name: Open Settings and more menu
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - E
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - F
      - Name: Open History
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - H
      - Name: Open Downloads
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - J
      - Name: Open Favorites
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - O
      - Name: Open Collections
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - Y
      - Name: Open search in sidebar
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - E
      - Name: Show or hide the favorites bar
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - B
      - Name: Save the current tab as a favorite
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - D
      - Name: Save all open tabs as favorites in a new folder
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - D
      - Name: Open Developer Tools
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - I
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - F12
      - Name: Open Send feedback dialog
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: true
          Alt: true
          Keys:
            - I
      - Name: Sign in as different user / browse as guest
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - M
      - Name: Open clear browsing data options
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - "<Delete>"
      - Name: Open Help
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - F1
      - Name: Turn caret browsing on or off
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - F7
      - Name: Enter or exit Immersive Reader
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - F9
  - SectionName: Web page
    Properties:
      - Name: Open find on page
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - F
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - F3
      - Name: Find next result
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - G
      - Name: Find previous result
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - G
      - Name: Reload the current page
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - R
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - F5
      - Name: "Reload, ignoring cached content"
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - R
        - Win: false
          Ctrl: false
          Shift: true
          Alt: false
          Keys:
            - F5
      - Name: Save the current page
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - S
      - Name: Print the current page
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - P
      - Name: Print using the system dialog
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - P
      - Name: Open a file in Edge
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - O
      - Name: View source
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - U
      - Name: Start or stop Read Aloud
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - U
      - Name: Paste without formatting
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - V
      - Name: Zoom in
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Plus
      - Name: Zoom out
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Minus
      - Name: Reset page zoom level
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - 0
      - Name: Stop loading page; close dialog or pop-up
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - "<Escape>"
      - Name: Scroll down a screen
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - "<Space>"
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - PageDown
      - Name: Scroll up a screen
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: true
          Alt: false
          Keys:
            - "<Space>"
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - PageUp
      - Name: Go to top of page
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - Home
      - Name: Go to bottom of page
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - End
      - Name: Go back
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - "<Left>"
      - Name: Go forward
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - "<Right>"
      - Name: Open home page in current tab
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - Home
  - SectionName: Focus
    Properties:
      - Name: Move focus to next pane
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - F6
      - Name: Move focus to previous pane
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: true
          Alt: false
          Keys:
            - F6
      - Name: Move focus to web content pane
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - F6
      - Name: Set focus on the favorites bar (first item)
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: true
          Alt: true
          Keys:
            - B
      - Name: Set focus on the app bar toolbar (first item)
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: true
          Alt: true
          Keys:
            - T
      - Name: Set focus on Settings and more button
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - F10
      - Name: Open context menu
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: true
          Alt: false
          Keys:
            - F10
