PackageName: Microsoft.Excel
Name: Excel
WindowFilter: "excel.exe"
BackgroundProcess: false
Shortcuts:
  - SectionName: Frequently used
    Properties:
      - Name: Open workbook
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - O
      - Name: Save workbook
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - S
      - Name: Close workbook
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - W
      - Name: Cut
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - X
      - Name: Copy
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - C
      - Name: Paste
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - V
      - Name: Paste Special
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - V
      - Name: Undo
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Z
      - Name: Redo or repeat last action
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Y
      - Name: Remove cell contents
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - Delete
      - Name: Find
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - F
      - Name: Find and replace
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - H
      - Name: Print
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - P
  - SectionName: Navigation
    Properties:
      - Name: Move to edge of data region
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "<Arrow>"
      - Name: Move to beginning of worksheet
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Home
      - Name: Move to last used cell
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - End
      - Name: Next worksheet
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - PageDown
      - Name: Previous worksheet
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - PageUp
      - Name: One screen to the right
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - PageDown
      - Name: One screen to the left
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - PageUp
      - Name: Open Go To dialog
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - G
      - Name: Zoom in
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - Plus
      - Name: Zoom out
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - Minus
  - SectionName: Selection
    Properties:
      - Name: Select entire worksheet
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - A
      - Name: Extend selection by one cell
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: true
          Alt: false
          Keys:
            - "<Arrow>"
      - Name: Extend selection to last nonblank cell
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - "<Arrow>"
      - Name: Extend selection to start of worksheet
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - Home
      - Name: Extend selection to last used cell
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - End
      - Name: Select entire column
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Space
      - Name: Select entire row
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: true
          Alt: false
          Keys:
            - Space
      - Name: Turn extend mode on
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - F8
      - Name: Start a new line in the same cell
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - "<Enter>"
      - Name: Fill selected range with current entry
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "<Enter>"
  - SectionName: Cell formatting
    Properties:
      - Name: Open Format Cells dialog
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "1"
      - Name: Bold
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - B
      - Name: Italic
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - I
      - Name: Underline
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - U
      - Name: Strikethrough
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "5"
      - Name: Apply General number format
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - "~"
      - Name: Apply Currency format
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - "$"
      - Name: Apply Percentage format
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - "%"
      - Name: Apply Date format
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - "#"
      - Name: Apply Time format
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - "@"
      - Name: Apply Number format
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - "!"
      - Name: Apply outline border
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - "&"
      - Name: Remove outline border
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - "_"
  - SectionName: Data entry and editing
    Properties:
      - Name: Edit active cell
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - F2
      - Name: Fill down
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - D
      - Name: Enter current date
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - ";"
      - Name: Enter current time
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - ":"
      - Name: Toggle formula display
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "`"
      - Name: Copy formula from cell above
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "'"
      - Name: Insert blank cells
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - Plus
      - Name: Delete selected cells
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Minus
      - Name: Insert hyperlink
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - K
      - Name: Flash Fill
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - E
      - Name: Quick Analysis
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Q
      - Name: Create Table
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - T
      - Name: Hide selected rows
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "9"
      - Name: Hide selected columns
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "0"
  - SectionName: Formulas and functions
    Properties:
      - Name: AutoSum
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - "="
      - Name: Insert function
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: true
          Alt: false
          Keys:
            - F3
      - Name: Calculate all worksheets
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - F9
      - Name: Calculate active worksheet
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: true
          Alt: false
          Keys:
            - F9
      - Name: Cycle absolute and relative references
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - F4
      - Name: Create embedded chart
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - F1
      - Name: Create chart on new sheet
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - F11
      - Name: Open macro dialog
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - F8
      - Name: Open Visual Basic Editor
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - F11
      - Name: Refresh data in current worksheet
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - F5
      - Name: Refresh all data in workbook
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - F5
