PackageName: Postman.Postman
Name: Postman
WindowFilter: "Postman.exe"
BackgroundProcess: false
Shortcuts:
  - SectionName: Tabs
    Properties:
      - Name: Close tab
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - W
      - Name: Force close tab
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - W
      - Name: Switch to next tab
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Tab
      - Name: Switch to previous tab
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - Tab
      - Name: Switch to tab at position (1–8)
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - '1 - 8'
      - Name: Switch to last tab
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "<9>"
      - Name: Reopen last closed tab
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - T
      - Name: New runner tab
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - R
      - Name: Search tabs
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - A
  - SectionName: Sidebar
    Properties:
      - Name: Search sidebar
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - F
      - Name: Next item
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - "<Down>"
      - Name: Previous item
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - "<Up>"
      - Name: Expand item
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - "<Right>"
      - Name: Expand all
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - "<Right>"
      - Name: Collapse item
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - "<Left>"
      - Name: Collapse all
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - "<Left>"
      - Name: Select item
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - "<Enter>"
      - Name: Rename item
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - E
      - Name: Cut item
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - X
      - Name: Copy item
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - C
      - Name: Paste item
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - V
      - Name: Duplicate item
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - D
      - Name: Delete item
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - "<Delete>"
  - SectionName: Request
    Properties:
      - Name: Request URL
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - L
      - Name: Save request
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - S
      - Name: Save request as
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - S
      - Name: Send request
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "<Enter>"
      - Name: Send and download request
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - "<Enter>"
  - SectionName: Interface
    Properties:
      - Name: Zoom in
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Plus
      - Name: Zoom out
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Minus
      - Name: Reset zoom
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "<0>"
      - Name: Toggle two-pane view
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - V
      - Name: Toggle left sidebar
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "\\"
      - Name: Toggle right sidebar
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - "\\"
      - Name: Toggle workbench
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - M
      - Name: Swap sidebars
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - S
      - Name: Reset layout
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - R
      - Name: Environment selector
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - E
  - SectionName: Window and modals
    Properties:
      - Name: New…
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - N
      - Name: New Postman window
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - N
      - Name: New console window
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - C
      - Name: Find
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - F
      - Name: Import
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - O
      - Name: Settings
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - ","
      - Name: Open shortcut help
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "/"
      - Name: Search
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - K
      - Name: Search in current workspace
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - K
      - Name: Open Postbot
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: true
          Keys:
            - P
      - Name: Open Vault
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - V
      - Name: Open browser tab
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - B
      - Name: Cancel conversation
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - C
      - Name: Accept all
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - Y
      - Name: Reject all
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "<Escape>"
  - SectionName: Console
    Properties:
      - Name: Clear console
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - K
      - Name: Show/hide console
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "`"
