PackageName: Telegram.TelegramDesktop
Name: Telegram Desktop
WindowFilter: "telegram.exe"
BackgroundProcess: true
Shortcuts:
  - SectionName: Chat navigation
    Properties:
      - Name: Move to next chat
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Tab
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - PageDown
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - "<Down>"
      - Name: Move to previous chat
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - Tab
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - PageUp
        - Win: false
          Ctrl: false
          Shift: false
          Alt: true
          Keys:
            - "<Up>"
      - Name: Go to previous folder
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - "<Up>"
      - Name: Go to next folder
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - "<Down>"
      - Name: Search in selected chat
        Recommended: true
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - F
      - Name: Exit selected chat / global search
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - "<Escape>"
  - SectionName: Messages
    Properties:
      - Name: Edit previous message
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - "<Up>"
      - Name: Delete currently selected message
        Shortcut:
        - Win: false
          Ctrl: false
          Shift: false
          Alt: false
          Keys:
            - "<Delete>"
      - Name: Start new line in input area
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - "<Enter>"
        - Win: false
          Ctrl: false
          Shift: true
          Alt: false
          Keys:
            - "<Enter>"
      - Name: Move cursor to start of multi-line message
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Home
  - SectionName: Text formatting
    Properties:
      - Name: Italic
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - I
      - Name: Bold
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - B
      - Name: Underline
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - U
      - Name: Strikethrough
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - X
      - Name: Monospace
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - M
      - Name: Remove formatting
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: true
          Alt: false
          Keys:
            - N
      - Name: Add URL to selection (link)
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - K
  - SectionName: Application
    Properties:
      - Name: Send file
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - O
      - Name: Open contacts
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - J
      - Name: Lock Telegram (if local password set)
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - L
      - Name: Minimize Telegram
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - M
      - Name: Minimize to system tray
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - W
      - Name: Quit Telegram
        Shortcut:
        - Win: false
          Ctrl: true
          Shift: false
          Alt: false
          Keys:
            - Q
