//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CmdPal.UI.ViewModels.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CmdPal.UI.ViewModels.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create another.
        /// </summary>
        public static string builtin_create_extension_create_another {
            get {
                return ResourceManager.GetString("builtin_create_extension_create_another", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder where the new extension will be created. The path will be created if it doesn&apos;t exist..
        /// </summary>
        public static string builtin_create_extension_directory_description {
            get {
                return ResourceManager.GetString("builtin_create_extension_directory_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output path.
        /// </summary>
        public static string builtin_create_extension_directory_label {
            get {
                return ResourceManager.GetString("builtin_create_extension_directory_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output path is required.
        /// </summary>
        public static string builtin_create_extension_directory_required {
            get {
                return ResourceManager.GetString("builtin_create_extension_directory_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the extension as it will appear to users..
        /// </summary>
        public static string builtin_create_extension_display_name_description {
            get {
                return ResourceManager.GetString("builtin_create_extension_display_name_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string builtin_create_extension_display_name_label {
            get {
                return ResourceManager.GetString("builtin_create_extension_display_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name is required.
        /// </summary>
        public static string builtin_create_extension_display_name_required {
            get {
                return ResourceManager.GetString("builtin_create_extension_display_name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string builtin_create_extension_name {
            get {
                return ResourceManager.GetString("builtin_create_extension_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid C# class name for the new extension project. It&apos;s recommended to include the word &quot;Extension&quot; in the name..
        /// </summary>
        public static string builtin_create_extension_name_description {
            get {
                return ResourceManager.GetString("builtin_create_extension_name_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension name.
        /// </summary>
        public static string builtin_create_extension_name_label {
            get {
                return ResourceManager.GetString("builtin_create_extension_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension name is required and must be a valid C# identifier (start with a letter or underscore, followed by letters, numbers, or underscores).
        /// </summary>
        public static string builtin_create_extension_name_required {
            get {
                return ResourceManager.GetString("builtin_create_extension_name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open directory.
        /// </summary>
        public static string builtin_create_extension_open_directory {
            get {
                return ResourceManager.GetString("builtin_create_extension_open_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Solution.
        /// </summary>
        public static string builtin_create_extension_open_solution {
            get {
                return ResourceManager.GetString("builtin_create_extension_open_solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new extension.
        /// </summary>
        public static string builtin_create_extension_page_title {
            get {
                return ResourceManager.GetString("builtin_create_extension_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create extension.
        /// </summary>
        public static string builtin_create_extension_submit {
            get {
                return ResourceManager.GetString("builtin_create_extension_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created your new extension!.
        /// </summary>
        public static string builtin_create_extension_success {
            get {
                return ResourceManager.GetString("builtin_create_extension_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new extension.
        /// </summary>
        public static string builtin_create_extension_title {
            get {
                return ResourceManager.GetString("builtin_create_extension_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new extension &apos;${displayName}&apos; was created in:.
        /// </summary>
        public static string builtin_created_in_text {
            get {
                return ResourceManager.GetString("builtin_created_in_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now that your extension project has been created, open the solution up in Visual Studio to start writing your extension code..
        /// </summary>
        public static string builtin_created_next_steps {
            get {
                return ResourceManager.GetString("builtin_created_next_steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to `${name}Page.cs` to start adding items to the list, or to `${name}CommandsProvider.cs` to add new commands..
        /// </summary>
        public static string builtin_created_next_steps_p2 {
            get {
                return ResourceManager.GetString("builtin_created_next_steps_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you&apos;re ready to test deploy the package locally with Visual Studio, then run the \&quot;Reload\&quot; command in the Command Palette to load your new extension..
        /// </summary>
        public static string builtin_created_next_steps_p3 {
            get {
                return ResourceManager.GetString("builtin_created_next_steps_p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next steps.
        /// </summary>
        public static string builtin_created_next_steps_title {
            get {
                return ResourceManager.GetString("builtin_created_next_steps_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new extension....
        /// </summary>
        public static string builtin_creating_extension_message {
            get {
                return ResourceManager.GetString("builtin_creating_extension_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string builtin_disabled_extension {
            get {
                return ResourceManager.GetString("builtin_disabled_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in commands.
        /// </summary>
        public static string builtin_display_name {
            get {
                return ResourceManager.GetString("builtin_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string builtin_home_name {
            get {
                return ResourceManager.GetString("builtin_home_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View log folder.
        /// </summary>
        public static string builtin_log_folder_command_name {
            get {
                return ResourceManager.GetString("builtin_log_folder_command_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View log.
        /// </summary>
        public static string builtin_log_name {
            get {
                return ResourceManager.GetString("builtin_log_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string builtin_log_page_name {
            get {
                return ResourceManager.GetString("builtin_log_page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View log messages.
        /// </summary>
        public static string builtin_log_subtitle {
            get {
                return ResourceManager.GetString("builtin_log_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View log.
        /// </summary>
        public static string builtin_log_title {
            get {
                return ResourceManager.GetString("builtin_log_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for apps, files and commands....
        /// </summary>
        public static string builtin_main_list_page_searchbar_placeholder {
            get {
                return ResourceManager.GetString("builtin_main_list_page_searchbar_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a project for a new Command Palette extension.
        /// </summary>
        public static string builtin_new_extension_subtitle {
            get {
                return ResourceManager.GetString("builtin_new_extension_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        public static string builtin_open_settings_name {
            get {
                return ResourceManager.GetString("builtin_open_settings_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Command Palette settings.
        /// </summary>
        public static string builtin_open_settings_subtitle {
            get {
                return ResourceManager.GetString("builtin_open_settings_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Command Palette.
        /// </summary>
        public static string builtin_quit_subtitle {
            get {
                return ResourceManager.GetString("builtin_quit_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Command Palette extensions.
        /// </summary>
        public static string builtin_reload_display_title {
            get {
                return ResourceManager.GetString("builtin_reload_display_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string builtin_reload_name {
            get {
                return ResourceManager.GetString("builtin_reload_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Command Palette extensions.
        /// </summary>
        public static string builtin_reload_subtitle {
            get {
                return ResourceManager.GetString("builtin_reload_subtitle", resourceCulture);
            }
        }
    }
}
