//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Awake.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Awake.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        internal static string AWAKE_1_HOUR {
            get {
                return ResourceManager.GetString("AWAKE_1_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute.
        /// </summary>
        internal static string AWAKE_1_MINUTE {
            get {
                return ResourceManager.GetString("AWAKE_1_MINUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        internal static string AWAKE_CHECKED {
            get {
                return ResourceManager.GetString("AWAKE_CHECKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string AWAKE_EXIT {
            get {
                return ResourceManager.GetString("AWAKE_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        internal static string AWAKE_HOURS {
            get {
                return ResourceManager.GetString("AWAKE_HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep awake indefinitely.
        /// </summary>
        internal static string AWAKE_KEEP_INDEFINITELY {
            get {
                return ResourceManager.GetString("AWAKE_KEEP_INDEFINITELY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep awake on interval.
        /// </summary>
        internal static string AWAKE_KEEP_ON_INTERVAL {
            get {
                return ResourceManager.GetString("AWAKE_KEEP_ON_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep screen on.
        /// </summary>
        internal static string AWAKE_KEEP_SCREEN_ON {
            get {
                return ResourceManager.GetString("AWAKE_KEEP_SCREEN_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep awake until expiration date and time.
        /// </summary>
        internal static string AWAKE_KEEP_UNTIL_EXPIRATION {
            get {
                return ResourceManager.GetString("AWAKE_KEEP_UNTIL_EXPIRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        internal static string AWAKE_MINUTES {
            get {
                return ResourceManager.GetString("AWAKE_MINUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off (keep using the selected power plan).
        /// </summary>
        internal static string AWAKE_OFF {
            get {
                return ResourceManager.GetString("AWAKE_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchecked.
        /// </summary>
        internal static string AWAKE_UNCHECKED {
            get {
                return ResourceManager.GetString("AWAKE_UNCHECKED", resourceCulture);
            }
        }
    }
}
