<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(RepoRoot)src\Common.Dotnet.CsWinRT.props" />
  <Import Project="$(RepoRoot)src\Common.SelfContained.props" />
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <OutputPath>$(RepoRoot)$(Platform)\$(Configuration)\tests\WorkspacesCsharpLibrary.UnitTests\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" />
    <ProjectReference Include="..\WorkspacesCsharpLibrary\WorkspacesCsharpLibrary.csproj" />
    <ProjectReference Include="..\WorkspacesEditor\WorkspacesEditor.csproj" />
  </ItemGroup>
</Project>
