<#
.SYNOPSIS
    Generates executive summary and category reports from categorized issues.

.DESCRIPTION
    Creates markdown reports for each category and an executive summary
    for the current triage run.

.PARAMETER InputPath
    Path to categorized issues JSON. Default: Generated Files/triage-issues/current-run/categorized-issues.json

.PARAMETER OutputPath
    Directory for generated reports. Default: Generated Files/triage-issues/current-run

.PARAMETER RepoUrl
    GitHub repository URL for issue links. Default: https://github.com/microsoft/PowerToys/issues

.EXAMPLE
    .\generate-summary.ps1
#>

param(
    [Parameter()]
    [string]$InputPath = "Generated Files/triage-issues/current-run/categorized-issues.json",
    
    [Parameter()]
    [string]$OutputPath = "Generated Files/triage-issues/current-run",
    
    [Parameter()]
    [string]$RepoUrl = "https://github.com/microsoft/PowerToys/issues"
)

$ErrorActionPreference = "Stop"

# Category display info
$CategoryInfo = @{
    "trending" = @{ emoji = "🔥"; name = "Trending"; priority = 1 }
    "needs-label" = @{ emoji = "🏷️"; name = "Needs-Label"; priority = 2 }
    "ready-for-fix" = @{ emoji = "✅"; name = "Ready-for-Fix"; priority = 3 }
    "needs-info" = @{ emoji = "❓"; name = "Needs-Info"; priority = 4 }
    "needs-clarification" = @{ emoji = "💬"; name = "Needs-Clarification"; priority = 5 }
    "closeable" = @{ emoji = "✔️"; name = "Closeable"; priority = 6 }
    "stale-waiting" = @{ emoji = "⏳"; name = "Stale-Waiting"; priority = 7 }
    "duplicate-candidate" = @{ emoji = "🔁"; name = "Duplicate-Candidate"; priority = 8 }
    "review-needed" = @{ emoji = "👀"; name = "Review-Needed"; priority = 9 }
}

# Load categorized issues
if (-not (Test-Path $InputPath)) {
    Write-Error "Input file not found: $InputPath. Run categorize-issues.ps1 first."
    exit 1
}

$data = Get-Content $InputPath | ConvertFrom-Json -AsHashtable

# Ensure output directories
New-Item -ItemType Directory -Force -Path $OutputPath | Out-Null
New-Item -ItemType Directory -Force -Path "$OutputPath/draft-replies" | Out-Null

# Group issues by category
$byCategory = @{}
foreach ($issueNum in $data.issues.Keys) {
    $issue = $data.issues[$issueNum]
    $cat = $issue.category
    if (-not $byCategory[$cat]) {
        $byCategory[$cat] = @()
    }
    $byCategory[$cat] += $issue
}

# Sort each category by priority
foreach ($cat in $byCategory.Keys) {
    $byCategory[$cat] = $byCategory[$cat] | Sort-Object priorityScore -Descending
}

# Generate Executive Summary
$summaryLines = @()
$summaryLines += "# Issue Triage Summary - $(Get-Date -Format 'yyyy-MM-dd')"
$summaryLines += ""
$summaryLines += "**Run Time**: $(Get-Date -Format 'HH:mm UTC') | **Issues Analyzed**: $($data.totalCategorized)"
$summaryLines += ""
$summaryLines += "## ⚡ Action Required by Category"
$summaryLines += ""
$summaryLines += "| Category | Count | Top Priority | Suggested Action |"
$summaryLines += "|----------|-------|--------------|------------------|"

foreach ($catId in $CategoryInfo.Keys | Sort-Object { $CategoryInfo[$_].priority }) {
    $info = $CategoryInfo[$catId]
    $issues = $byCategory[$catId]
    
    if ($issues -and $issues.Count -gt 0) {
        $top = $issues[0]
        $topLink = "[#$($top.number)]($RepoUrl/$($top.number))"
        $topInfo = $top.categoryReason
        if ($topInfo.Length -gt 40) { $topInfo = $topInfo.Substring(0, 37) + "..." }
        
        $summaryLines += "| $($info.emoji) $($info.name) | $($issues.Count) | $topLink | $topInfo |"
    }
}

$summaryLines += ""
$summaryLines += "## 🎯 Top 10 Priority Actions"
$summaryLines += ""

# Get top 10 across all categories
$allIssues = @()
foreach ($cat in $byCategory.Keys) {
    $allIssues += $byCategory[$cat]
}
$topIssues = $allIssues | Sort-Object priorityScore -Descending | Select-Object -First 10

$priority = 1
foreach ($issue in $topIssues) {
    $info = $CategoryInfo[$issue.category]
    $urgency = if ($issue.priorityScore -ge 80) { "**[Urgent]**" } 
               elseif ($issue.priorityScore -ge 60) { "**[High]**" }
               elseif ($issue.priorityScore -ge 40) { "[Medium]" }
               else { "[Low]" }
    
    $summaryLines += "$priority. $urgency $($info.emoji) [#$($issue.number)]($RepoUrl/$($issue.number)) - $($issue.categoryReason)"
    $priority++
}

$summaryLines += ""
$summaryLines += "## 📁 Detailed Reports"
$summaryLines += ""

foreach ($catId in $CategoryInfo.Keys | Sort-Object { $CategoryInfo[$_].priority }) {
    $info = $CategoryInfo[$catId]
    $issues = $byCategory[$catId]
    
    if ($issues -and $issues.Count -gt 0) {
        $summaryLines += "- [$($info.emoji) $($info.name)](./$catId.md) ($($issues.Count) issues)"
    }
}

$summaryLines += ""
$summaryLines += "---"
$summaryLines += "*Generated by continuous-issue-triage skill*"

$summaryLines -join "`n" | Set-Content "$OutputPath/summary.md"
Write-Host "Generated: summary.md"

# Generate individual category reports
foreach ($catId in $byCategory.Keys) {
    $info = $CategoryInfo[$catId]
    $issues = $byCategory[$catId]
    
    if (-not $issues -or $issues.Count -eq 0) { continue }
    
    $reportLines = @()
    $reportLines += "# $($info.emoji) $($info.name) Issues"
    $reportLines += ""
    $reportLines += "**Total**: $($issues.Count) issues"
    $reportLines += ""
    $reportLines += "## Overview"
    $reportLines += ""
    $reportLines += "| # | Issue | Priority | Reason | Labels |"
    $reportLines += "|---|-------|----------|--------|--------|"
    
    foreach ($issue in $issues) {
        $labelStr = ($issue.labels | Select-Object -First 3) -join ", "
        if ($issue.labels.Count -gt 3) { $labelStr += "..." }
        $reason = $issue.categoryReason
        if ($reason.Length -gt 50) { $reason = $reason.Substring(0, 47) + "..." }
        
        $reportLines += "| [#$($issue.number)]($RepoUrl/$($issue.number)) | $($issue.title.Substring(0, [Math]::Min(50, $issue.title.Length))) | $($issue.priorityScore)/100 | $reason | $labelStr |"
    }
    
    $reportLines += ""
    $reportLines += "## Detailed Breakdown"
    $reportLines += ""
    
    foreach ($issue in $issues) {
        $reportLines += "### [#$($issue.number)]($RepoUrl/$($issue.number)): $($issue.title)"
        $reportLines += ""
        $reportLines += "- **Priority Score**: $($issue.priorityScore)/100"
        $reportLines += "- **Category Reason**: $($issue.categoryReason)"
        $reportLines += "- **Suggested Action**: $($issue.suggestedAction)"
        $reportLines += "- **Reactions**: 👍 $($issue.reactions.thumbsUp) | ❤️ $($issue.reactions.heart)"
        $reportLines += "- **Comments**: $($issue.totalComments) total ($($issue.newComments) new)"
        $reportLines += "- **Labels**: $($issue.labels -join ', ')"
        
        if ($issue.additionalData) {
            if ($issue.additionalData.suggestedLabels) {
                $reportLines += "- **Suggested Labels**: $($issue.additionalData.suggestedLabels -join ', ') (confidence: $($issue.additionalData.labelConfidence)%)"
            }
            if ($issue.additionalData.missingItems) {
                $reportLines += "- **Missing Info**: $($issue.additionalData.missingItems -join ', ')"
            }
            if ($issue.additionalData.mergedPRs) {
                $reportLines += "- **Merged PRs**: #$($issue.additionalData.mergedPRs -join ', #')"
            }
            if ($issue.additionalData.daysWaiting) {
                $reportLines += "- **Days Waiting**: $($issue.additionalData.daysWaiting)"
            }
        }
        
        $reportLines += ""
        $reportLines += "---"
        $reportLines += ""
    }
    
    $reportLines -join "`n" | Set-Content "$OutputPath/$catId.md"
    Write-Host "Generated: $catId.md"
}

Write-Host ""
Write-Host "All reports generated in: $OutputPath"
Write-Host "Start with: summary.md"
