import "ProcessResult.idl";

namespace PowerToys
{
    namespace FileLocksmithLib
    {
        namespace Interop
        {
            [default_interface] static runtimeclass NativeMethods {
                static PowerToys.FileLocksmithLib.Interop.ProcessResult[] FindProcessesRecursive(String[] paths);
                static String PidToFullPath(UInt32 pid);
                static String[] ReadPathsFromFile();
                static Boolean StartAsElevated(String[] paths);
                static Boolean SetDebugPrivilege();
                static Boolean IsProcessElevated();
            }
        }
    }
}
