namespace PowerToys
{
    namespace FileLocksmithLib
    {
        namespace Interop
        {
            [default_interface] runtimeclass ProcessResult {
                ProcessResult(String name, UInt32 pid, String user, String[] files);
                String name{ get; };
                UInt32 pid{ get; };
                String user{ get; };
                String[] files{ get; };
            };
        }
    }
}