import "shobjidl.idl";

[
	uuid(09082E28-A5CA-47A7-8571-A2236C411E91),
	version(3.1)
]
library ImageResizerExtLib
{
	[uuid(51B4D7E5-7568-4234-B4BB-47FB3C016A69)]
	coclass ContextMenuHandler
	{
		[default] interface IShellExtInit;
		interface IContextMenu;
	};
};
