//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CmdPal.Ext.RaycastStore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CmdPal.Ext.RaycastStore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uninstalling.
        /// </summary>
        public static string extension_error_uninstalling {
            get {
                return ResourceManager.GetString("extension_error_uninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to uninstall.
        /// </summary>
        public static string extension_failed_to_uninstall {
            get {
                return ResourceManager.GetString("extension_failed_to_uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string extension_install {
            get {
                return ResourceManager.GetString("extension_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string extension_uninstall {
            get {
                return ResourceManager.GetString("extension_uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uninstalled.
        /// </summary>
        public static string extension_uninstalled {
            get {
                return ResourceManager.GetString("extension_uninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling.
        /// </summary>
        public static string extension_uninstalling {
            get {
                return ResourceManager.GetString("extension_uninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search and install Raycast extensions for Command Palette.
        /// </summary>
        public static string raycast_store_browse_subtitle {
            get {
                return ResourceManager.GetString("raycast_store_browse_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Raycast Extensions.
        /// </summary>
        public static string raycast_store_browse_title {
            get {
                return ResourceManager.GetString("raycast_store_browse_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raycast Extension Store.
        /// </summary>
        public static string raycast_store_display_name {
            get {
                return ResourceManager.GetString("raycast_store_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage installed Raycast extensions.
        /// </summary>
        public static string raycast_store_installed_subtitle {
            get {
                return ResourceManager.GetString("raycast_store_installed_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Raycast Extensions.
        /// </summary>
        public static string raycast_store_installed_title {
            get {
                return ResourceManager.GetString("raycast_store_installed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing extension....
        /// </summary>
        public static string raycast_store_installing {
            get {
                return ResourceManager.GetString("raycast_store_installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading extensions....
        /// </summary>
        public static string raycast_store_loading {
            get {
                return ResourceManager.GetString("raycast_store_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No extensions found.
        /// </summary>
        public static string raycast_store_no_extensions_found {
            get {
                return ResourceManager.GetString("raycast_store_no_extensions_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.js Required.
        /// </summary>
        public static string raycast_store_nodejs_required {
            get {
                return ResourceManager.GetString("raycast_store_nodejs_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub API rate limit reached. Set GITHUB_TOKEN for higher limits..
        /// </summary>
        public static string raycast_store_rate_limited {
            get {
                return ResourceManager.GetString("raycast_store_rate_limited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search extensions by name, author, or description....
        /// </summary>
        public static string raycast_store_search_placeholder {
            get {
                return ResourceManager.GetString("raycast_store_search_placeholder", resourceCulture);
            }
        }
    }
}
