//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CmdPal.Ext.TimeDate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CmdPal.Ext.TimeDate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy failed.
        /// </summary>
        public static string Microsoft_plugin_timedate_copy_failed {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_copy_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy value (Ctrl+C).
        /// </summary>
        public static string Microsoft_plugin_timedate_CopyToClipboard {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Microsoft_plugin_timedate_Date {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        public static string Microsoft_plugin_timedate_DateAndTime {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time UTC.
        /// </summary>
        public static string Microsoft_plugin_timedate_DateAndTimeUtc {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_DateAndTimeUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day (Week day).
        /// </summary>
        public static string Microsoft_plugin_timedate_Day {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month and day.
        /// </summary>
        public static string Microsoft_plugin_timedate_DayMonth {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_DayMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of the month.
        /// </summary>
        public static string Microsoft_plugin_timedate_DayOfMonth {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_DayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of the week (Week day).
        /// </summary>
        public static string Microsoft_plugin_timedate_DayOfWeek {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of the year.
        /// </summary>
        public static string Microsoft_plugin_timedate_DayOfYear {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_DayOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Era.
        /// </summary>
        public static string Microsoft_plugin_timedate_Era {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Era", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Era abbreviation.
        /// </summary>
        public static string Microsoft_plugin_timedate_EraAbbreviation {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_EraAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid prefixes: &apos;u&apos; for Unix Timestamp, &apos;ums&apos; for Unix Timestamp in milliseconds, &apos;ft&apos; for Windows file time.
        /// </summary>
        public static string Microsoft_plugin_timedate_ErrorResultSubTitle {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_ErrorResultSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid number input.
        /// </summary>
        public static string Microsoft_plugin_timedate_ErrorResultTitle {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_ErrorResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time in filename-compatible format.
        /// </summary>
        public static string Microsoft_plugin_timedate_filename_compatible {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_filename_compatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Microsoft_plugin_timedate_Hour {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid prefixes: &apos;u&apos; for Unix Timestamp, &apos;ums&apos; for Unix Timestamp in milliseconds, &apos;ft&apos; for Windows file time.
        /// </summary>
        public static string Microsoft_plugin_timedate_InvalidInput_ErrorMessageSubTitle {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_InvalidInput_ErrorMessageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid input.
        /// </summary>
        public static string Microsoft_plugin_timedate_InvalidInput_ErrorMessageTitle {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_InvalidInput_ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO 8601.
        /// </summary>
        public static string Microsoft_plugin_timedate_Iso8601 {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Iso8601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO 8601 UTC.
        /// </summary>
        public static string Microsoft_plugin_timedate_Iso8601Utc {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Iso8601Utc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO 8601 with time zone.
        /// </summary>
        public static string Microsoft_plugin_timedate_Iso8601Zone {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Iso8601Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO 8601 UTC with time zone.
        /// </summary>
        public static string Microsoft_plugin_timedate_Iso8601ZoneUtc {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Iso8601ZoneUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Microsoft_plugin_timedate_main_page_name {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_main_page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time &amp;amp; Date.
        /// </summary>
        public static string Microsoft_plugin_timedate_main_page_title {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_main_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millisecond.
        /// </summary>
        public static string Microsoft_plugin_timedate_Millisecond {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Microsoft_plugin_timedate_Minute {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Microsoft_plugin_timedate_Month {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month of the year.
        /// </summary>
        public static string Microsoft_plugin_timedate_MonthOfYear {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_MonthOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month and year.
        /// </summary>
        public static string Microsoft_plugin_timedate_MonthYear {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_MonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string Microsoft_plugin_timedate_Now {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now UTC.
        /// </summary>
        public static string Microsoft_plugin_timedate_NowUtc {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_NowUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search values or type a custom time stamp....
        /// </summary>
        public static string Microsoft_plugin_timedate_placeholder_text {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_placeholder_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides time and date values in different formats.
        /// </summary>
        public static string Microsoft_plugin_timedate_plugin_description {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar week.
        /// </summary>
        public static string Microsoft_plugin_timedate_plugin_description_example_calendarWeek {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_plugin_description_example_calendarWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Microsoft_plugin_timedate_plugin_description_example_day {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_plugin_description_example_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Microsoft_plugin_timedate_plugin_description_example_time {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_plugin_description_example_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time and Date.
        /// </summary>
        public static string Microsoft_plugin_timedate_plugin_name {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC1123.
        /// </summary>
        public static string Microsoft_plugin_timedate_Rfc1123 {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Rfc1123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for; and; nor; but; or; so.
        /// </summary>
        public static string Microsoft_plugin_timedate_Search_ConjunctionList {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Search_ConjunctionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Microsoft_plugin_timedate_SearchTagDate {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SearchTagDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current date; Now.
        /// </summary>
        public static string Microsoft_plugin_timedate_SearchTagDateNow {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SearchTagDateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year; Calendar era; Date.
        /// </summary>
        public static string Microsoft_plugin_timedate_SearchTagEra {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SearchTagEra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current year; Current calendar era; Current date; Now.
        /// </summary>
        public static string Microsoft_plugin_timedate_SearchTagEraNow {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SearchTagEraNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time; Time and Date.
        /// </summary>
        public static string Microsoft_plugin_timedate_SearchTagFormat {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SearchTagFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current date and time; Current time and date; Now.
        /// </summary>
        public static string Microsoft_plugin_timedate_SearchTagFormatNow {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SearchTagFormatNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Microsoft_plugin_timedate_SearchTagTime {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SearchTagTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Time; Now.
        /// </summary>
        public static string Microsoft_plugin_timedate_SearchTagTimeNow {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SearchTagTimeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string Microsoft_plugin_timedate_Second {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system setting.
        /// </summary>
        public static string Microsoft_plugin_timedate_Setting_UseSystemSetting {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Setting_UseSystemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show date with weekday and name of month.
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingDateWithWeekday {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingDateWithWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting applies to the &apos;Date&apos; and &apos;Now&apos; result..
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingDateWithWeekday_Description {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingDateWithWeekday_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First day of the week.
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingFirstDayOfWeek {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingFirstDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingFirstDayOfWeek_Friday {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingFirstDayOfWeek_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingFirstDayOfWeek_Monday {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingFirstDayOfWeek_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingFirstDayOfWeek_Saturday {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingFirstDayOfWeek_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingFirstDayOfWeek_Sunday {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingFirstDayOfWeek_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingFirstDayOfWeek_Thursday {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingFirstDayOfWeek_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingFirstDayOfWeek_Tuesday {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingFirstDayOfWeek_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingFirstDayOfWeek_Wednesday {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingFirstDayOfWeek_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First week of the year.
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingFirstWeekRule {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingFirstWeekRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the calendar rule for the first week of the year..
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingFirstWeekRule_Description {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingFirstWeekRule_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First day of year.
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingFirstWeekRule_FirstDay {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingFirstWeekRule_FirstDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First four day week.
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingFirstWeekRule_FirstFourDayWeek {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingFirstWeekRule_FirstFourDayWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First full week.
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingFirstWeekRule_FirstFullWeek {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingFirstWeekRule_FirstFullWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide &apos;Invalid number input&apos; error message on global queries.
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingHideNumberMessageOnGlobalQuery {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingHideNumberMessageOnGlobalQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only &apos;Time&apos;, &apos;Date&apos; and &apos;Now&apos; result for system time on global queries.
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingOnlyDateTimeNowGlobal {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingOnlyDateTimeNowGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regardless of this setting, for global queries the first word of the query has to be a complete match..
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingOnlyDateTimeNowGlobal_Description {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingOnlyDateTimeNowGlobal_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show time with seconds.
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingTimeWithSeconds {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingTimeWithSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting applies to the &apos;Time&apos; and &apos;Now&apos; result..
        /// </summary>
        public static string Microsoft_plugin_timedate_SettingTimeWithSeconds_Description {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SettingTimeWithSeconds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or press Ctrl+C to copy.
        /// </summary>
        public static string Microsoft_plugin_timedate_SubTitleNote {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_SubTitleNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Microsoft_plugin_timedate_Time {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time UTC.
        /// </summary>
        public static string Microsoft_plugin_timedate_TimeUtc {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_TimeUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative search tags:.
        /// </summary>
        public static string Microsoft_plugin_timedate_ToolTipAlternativeSearchTag {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_ToolTipAlternativeSearchTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal time format: YYYY-MM-DD hh:mm:ss.
        /// </summary>
        public static string Microsoft_plugin_timedate_UniversalTime {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_UniversalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unix epoch time.
        /// </summary>
        public static string Microsoft_plugin_timedate_Unix {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Unix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unix epoch time in milliseconds.
        /// </summary>
        public static string Microsoft_plugin_timedate_Unix_Milliseconds {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Unix_Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week of the month.
        /// </summary>
        public static string Microsoft_plugin_timedate_WeekOfMonth {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_WeekOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week of the year (Calendar week, Week number).
        /// </summary>
        public static string Microsoft_plugin_timedate_WeekOfYear {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_WeekOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows file time (Int64 number).
        /// </summary>
        public static string Microsoft_plugin_timedate_WindowsFileTime {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_WindowsFileTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Microsoft_plugin_timedate_Year {
            get {
                return ResourceManager.GetString("Microsoft_plugin_timedate_Year", resourceCulture);
            }
        }
    }
}
