//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wox.Plugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wox.Plugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to load plugin:.
        /// </summary>
        public static string FailedToLoadPluginDescription {
            get {
                return ResourceManager.GetString("FailedToLoadPluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please report the bug to https://aka.ms/powerToysReportBug. (For third-party plugins, please contact the plugin author.).
        /// </summary>
        public static string FailedToLoadPluginDescriptionPartTwo {
            get {
                return ResourceManager.GetString("FailedToLoadPluginDescriptionPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerToys Run - Plugin Loading Error.
        /// </summary>
        public static string FailedToLoadPluginTitle {
            get {
                return ResourceManager.GetString("FailedToLoadPluginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On all Desktops.
        /// </summary>
        public static string VirtualDesktopHelper_AllDesktops {
            get {
                return ResourceManager.GetString("VirtualDesktopHelper_AllDesktops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop {0}.
        /// </summary>
        public static string VirtualDesktopHelper_Desktop {
            get {
                return ResourceManager.GetString("VirtualDesktopHelper_Desktop", resourceCulture);
            }
        }
    }
}
