//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CmdPal.Ext.Apps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CmdPal.Ext.Apps.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Apps.
        /// </summary>
        internal static string all_apps {
            get {
                return ResourceManager.GetString("all_apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string application {
            get {
                return ResourceManager.GetString("application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include apps found on the desktop.
        /// </summary>
        internal static string enable_desktop_source {
            get {
                return ResourceManager.GetString("enable_desktop_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include apps anywhere on the %PATH%.
        /// </summary>
        internal static string enable_path_environment_variable_source {
            get {
                return ResourceManager.GetString("enable_path_environment_variable_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include apps registered in the Registry.
        /// </summary>
        internal static string enable_registry_source {
            get {
                return ResourceManager.GetString("enable_registry_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include apps found in the Start Menu.
        /// </summary>
        internal static string enable_start_menu_source {
            get {
                return ResourceManager.GetString("enable_start_menu_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string folder {
            get {
                return ResourceManager.GetString("folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed apps.
        /// </summary>
        internal static string installed_apps {
            get {
                return ResourceManager.GetString("installed_apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet shortcut application.
        /// </summary>
        internal static string internet_shortcut_application {
            get {
                return ResourceManager.GetString("internet_shortcut_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open containing folder.
        /// </summary>
        internal static string open_containing_folder {
            get {
                return ResourceManager.GetString("open_containing_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open location.
        /// </summary>
        internal static string open_location {
            get {
                return ResourceManager.GetString("open_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open path in console.
        /// </summary>
        internal static string open_path_in_console {
            get {
                return ResourceManager.GetString("open_path_in_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaged application.
        /// </summary>
        internal static string packaged_application {
            get {
                return ResourceManager.GetString("packaged_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as administrator.
        /// </summary>
        internal static string run_as_administrator {
            get {
                return ResourceManager.GetString("run_as_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as different user.
        /// </summary>
        internal static string run_as_different_user {
            get {
                return ResourceManager.GetString("run_as_different_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run command.
        /// </summary>
        internal static string run_command {
            get {
                return ResourceManager.GetString("run_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string run_command_action {
            get {
                return ResourceManager.GetString("run_command_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search installed apps.
        /// </summary>
        internal static string search_installed_apps {
            get {
                return ResourceManager.GetString("search_installed_apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search installed apps....
        /// </summary>
        internal static string search_installed_apps_placeholder {
            get {
                return ResourceManager.GetString("search_installed_apps_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental: When enabled, Command Palette will load thumbnails from the Windows Shell. Using thumbnails may cause the app to crash on launch.
        /// </summary>
        internal static string use_thumbnails_setting_description {
            get {
                return ResourceManager.GetString("use_thumbnails_setting_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use thumbnails for apps.
        /// </summary>
        internal static string use_thumbnails_setting_label {
            get {
                return ResourceManager.GetString("use_thumbnails_setting_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web application.
        /// </summary>
        internal static string web_application {
            get {
                return ResourceManager.GetString("web_application", resourceCulture);
            }
        }
    }
}
