variables:
  - name: runCodesignValidationInjectionBG
    value: false
  - name: EnablePipelineCache
    value: true

parameters:
  - name: buildPlatforms
    type: object
    default:
      - x64
      - arm64
  - name: enableMsBuildCaching
    type: boolean
    default: false
  - name: msBuildCacheIsReadOnly
    type: boolean
    default: true
  - name: runTests
    type: boolean
    default: true
  - name: useVS2026
    type: boolean
    default: false
  - name: useLatestWebView2
    type: boolean
    default: false
  - name: useLatestWinAppSDK
    type: boolean
    default: false
  - name: winAppSDKVersionNumber
    type: string
    default: 1.6
  - name: useExperimentalVersion
    type: boolean
    default: false

stages:
  - ${{ each platform in parameters.buildPlatforms }}:
    - stage: Build_${{ platform }}
      displayName: Build ${{ platform }}
      dependsOn: []
      jobs:
        - template: job-build-project.yml
          parameters:
            pool:
              ${{ if eq(variables['System.CollectionId'], 'cb55739e-4afe-46a3-970f-1b49d8ee7564') }}:
                name: SHINE-INT-L
              ${{ else }}:
                name: SHINE-OSS-L
              ${{ if eq(parameters.useVS2026, true) }}:
                demands: ImageOverride -equals SHINE-VS18-Latest
            buildPlatforms:
              - ${{ platform }}
            buildConfigurations: [Release]
            enablePackageCaching: true
            enableMsBuildCaching: ${{ parameters.enableMsBuildCaching }}
            msBuildCacheIsReadOnly: ${{ parameters.msBuildCacheIsReadOnly }}
            runTests: ${{ parameters.runTests }}
            useVS2026: ${{ parameters.useVS2026 }}
            useLatestWinAppSDK: ${{ parameters.useLatestWinAppSDK }}
            ${{ if eq(parameters.useLatestWinAppSDK, true) }}:
              winAppSDKVersionNumber: ${{ parameters.winAppSDKVersionNumber }}
              useExperimentalVersion: ${{ parameters.useExperimentalVersion }}
            timeoutInMinutes: 90

  - stage: Build_SDK
    displayName: Build Command Palette Toolkit SDK
    dependsOn: []
    jobs:
      - template: job-build-sdk.yml
        parameters:
          pool:
            ${{ if eq(variables['System.CollectionId'], 'cb55739e-4afe-46a3-970f-1b49d8ee7564') }}:
              name: SHINE-INT-L
            ${{ else }}:
              name: SHINE-OSS-L
            ${{ if eq(parameters.useVS2026, true) }}:
              demands: ImageOverride -equals SHINE-VS18-Latest
          buildConfigurations: [Release]
          official: false
          codeSign: false
