# Template for official build path: Download Official Build + Build UI Tests Only + Run Tests
parameters:
  - name: platform
    type: string
  - name: buildSource
    type: string
  - name: specificBuildId
    type: string
    default: 'xxxx'
  - name: useLatestWebView2
    type: boolean
    default: false
  - name: uiTestModules
    type: object
    default: []

stages:
  # Stage 1: Build UI Tests Only
  - stage: BuildUITests_${{ parameters.platform }}
    displayName: Build UI Tests Only ${{ parameters.platform }}
    dependsOn: []
    jobs:
      - template: job-build-ui-tests.yml
        parameters:
          pool:
            ${{ if eq(variables['System.CollectionId'], 'cb55739e-4afe-46a3-970f-1b49d8ee7564') }}:
              name: SHINE-INT-L
            ${{ else }}:
              name: SHINE-OSS-L
          buildPlatforms:
            - ${{ parameters.platform }}
          uiTestModules: ${{ parameters.uiTestModules }}

  # Stage 2: Run UI Tests with Official Build
  - ${{ if eq(parameters.platform, 'x64') }}:
    - stage: Test_x64Win10_OfficialBuild
      displayName: Test x64Win10 (Official Build)
      dependsOn: BuildUITests_${{ parameters.platform }}
      jobs:
        - template: job-test-project.yml
          parameters:
            platform: x64Win10
            configuration: Release
            useLatestWebView2: ${{ parameters.useLatestWebView2 }}
            buildSource: ${{ parameters.buildSource }}
            specificBuildId: ${{ parameters.specificBuildId }}
            uiTestModules: ${{ parameters.uiTestModules }}

        # Additional per-user installation test
        - template: job-test-project.yml
          parameters:
            platform: x64Win10
            configuration: Release
            useLatestWebView2: ${{ parameters.useLatestWebView2 }}
            buildSource: ${{ parameters.buildSource }}
            specificBuildId: ${{ parameters.specificBuildId }}
            uiTestModules: ${{ parameters.uiTestModules }}
            installMode: 'peruser'
            jobSuffix: '_PerUser'

    - stage: Test_x64Win11_OfficialBuild
      displayName: Test x64Win11 (Official Build)
      dependsOn: BuildUITests_${{ parameters.platform }}
      jobs:
        - template: job-test-project.yml
          parameters:
            platform: x64Win11
            configuration: Release
            useLatestWebView2: ${{ parameters.useLatestWebView2 }}
            buildSource: ${{ parameters.buildSource }}
            specificBuildId: ${{ parameters.specificBuildId }}
            uiTestModules: ${{ parameters.uiTestModules }}

        # Additional per-user installation test
        - template: job-test-project.yml
          parameters:
            platform: x64Win11
            configuration: Release
            useLatestWebView2: ${{ parameters.useLatestWebView2 }}
            buildSource: ${{ parameters.buildSource }}
            specificBuildId: ${{ parameters.specificBuildId }}
            uiTestModules: ${{ parameters.uiTestModules }}
            installMode: 'peruser'
            jobSuffix: '_PerUser'

  - ${{ if ne(parameters.platform, 'x64') }}:
    - stage: Test_${{ parameters.platform }}_OfficialBuild
      displayName: Test ${{ parameters.platform }} (Official Build)
      dependsOn: BuildUITests_${{ parameters.platform }}
      jobs:
        - template: job-test-project.yml
          parameters:
            platform: ${{ parameters.platform }}
            configuration: Release
            useLatestWebView2: ${{ parameters.useLatestWebView2 }}
            buildSource: ${{ parameters.buildSource }}
            specificBuildId: ${{ parameters.specificBuildId }}
            uiTestModules: ${{ parameters.uiTestModules }}

        # Additional per-user installation test
        - template: job-test-project.yml
          parameters:
            platform: ${{ parameters.platform }}
            configuration: Release
            useLatestWebView2: ${{ parameters.useLatestWebView2 }}
            buildSource: ${{ parameters.buildSource }}
            specificBuildId: ${{ parameters.specificBuildId }}
            uiTestModules: ${{ parameters.uiTestModules }}
            installMode: 'peruser'
            jobSuffix: '_PerUser'
