trigger: none
pr: none
schedules:
  - cron: "0 0 * * *" # every day at midnight
    displayName: "Daily midnight Build"
    branches:
      include:
        - main
    always: false # only run if there's code changes!

name: $(BuildDefinitionName)_$(date:yyMM).$(date:dd)$(rev:rrr)

parameters:
  - name: buildPlatforms
    type: object
    default:
      - x64
      - arm64
  - name: enableMsBuildCaching
    type: boolean
    displayName: "Enable MSBuild Caching"
    default: false
  - name: runTests
    type: boolean
    displayName: "Run Tests"
    default: true
  - name: useVS2026
    type: boolean
    displayName: "Build with VS2026"
    default: false
  - name: useLatestWinAppSDK
    type: boolean
    default: true
  - name: winAppSDKVersionNumber
    type: string
    default: 1.8
  - name: useExperimentalVersion
    type: boolean
    default: false

extends:
  template: templates/pipeline-ci-build.yml
  parameters:
    buildPlatforms: ${{ parameters.buildPlatforms }}
    ${{ if eq(variables['System.PullRequest.IsFork'], 'False') }}:
      enableMsBuildCaching: ${{ parameters.enableMsBuildCaching }}
    runTests: ${{ parameters.runTests }}
    useVS2026: ${{ parameters.useVS2026 }}
    useLatestWinAppSDK: ${{ parameters.useLatestWinAppSDK }}
    winAppSDKVersionNumber: ${{ parameters.winAppSDKVersionNumber }}
    useExperimentalVersion: ${{ parameters.useExperimentalVersion }}
