trigger: none
pr: none
schedules:
  - cron: "0 0 * * *" # every day at midnight
    displayName: "Daily midnight Build"
    branches:
      include:
        - main
    always: false # only run if there's code changes!

name: $(BuildDefinitionName)_$(date:yyMM).$(date:dd)$(rev:rrr)

parameters:
  - name: buildPlatforms
    type: object
    default:
      - x64
      - arm64
  - name: enableMsBuildCaching
    type: boolean
    displayName: "Enable MSBuild Caching"
    default: false
  - name: runTests
    type: boolean
    displayName: "Run Tests"
    default: true
  - name: useVSPreview
    type: boolean
    displayName: "Build Using Visual Studio Preview"
    default: false
  - name: useLatestWinAppSDK
    type: boolean
    default: true
  - name: winAppSDKVersionNumber
    type: string
    default: 1.8
  - name: useExperimentalVersion
    type: boolean
    default: false
  # Artifact mode parameters (optional)
  - name: useArtifactSource
    type: boolean
    displayName: "Use Artifact Source (instead of feed)"
    default: false
  - name: buildId
    type: string
    displayName: "Windows App SDK Build ID (for artifact mode)"
    default: ''
  - name: azureDevOpsProject
    type: string
    displayName: "Source Project (for artifact mode)"
    default: 'ProjectReunion'
  - name: artifactName
    type: string
    displayName: "Artifact Name (for artifact mode)"
    default: 'WindowsAppSDK_Nuget_And_MSIX'

extends:
  template: templates/pipeline-ci-build.yml
  parameters:
    buildPlatforms: ${{ parameters.buildPlatforms }}
    ${{ if eq(variables['System.PullRequest.IsFork'], 'False') }}:
      enableMsBuildCaching: ${{ parameters.enableMsBuildCaching }}
    runTests: ${{ parameters.runTests }}
    useVSPreview: ${{ parameters.useVSPreview }}
    useLatestWinAppSDK: ${{ parameters.useLatestWinAppSDK }}
    winAppSDKVersionNumber: ${{ parameters.winAppSDKVersionNumber }}
    useExperimentalVersion: ${{ parameters.useExperimentalVersion }}
    useArtifactSource: ${{ parameters.useArtifactSource }}
    buildId: ${{ parameters.buildId }}
    azureDevOpsProject: ${{ parameters.azureDevOpsProject }}
    artifactName: ${{ parameters.artifactName }}
