namespace BackgroundActivator
{
    [version(1)]
    runtimeclass BackgroundHandler
    {
        BackgroundHandler();
    
        void Run(Windows.ApplicationModel.Background.IBackgroundTaskInstance taskInstance);
    }
}
