// Copyright (c) Microsoft Corporation
// The Microsoft Corporation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

// <auto-generated/>
#nullable enable

namespace MouseJump.Common.Win32Gen;

using System.ComponentModel;
using System.Runtime.CompilerServices;

/// <summary>
/// Wraps the result of a Win32 api call so callers can inspect or throw on
/// failure through a fluent interface, without repeating error-handling
/// boilerplate at every call site. A struct so wrapping a call doesn't
/// allocate, since these are expected to sit on hot paths.
/// </summary>
internal readonly struct Win32Result<T>
{
    public Win32Result(
        T value,
        bool success,
        int? lastError = null,
        [CallerMemberName] string memberName = "")
    {
        this.Value = value;
        this.Success = success;
        this.LastError = lastError;
        this.MemberName = memberName;
    }

    public T Value { get; }

    public bool Success { get; }

    public bool Failure => !this.Success;

    public int? LastError { get; }

    public string MemberName { get; }

    /// <summary>
    /// Throws a <see cref="Win32Exception"/> if the underlying api call failed.
    /// </summary>
    public Win32Result<T> ThrowIfFailed()
    {
        if (this.Failure)
        {
            if (this.LastError is null)
            {
                throw new Win32Exception(
                    string.Join(Environment.NewLine,
                        $"{this.MemberName} failed.",
                        $"ReturnValue: {this.Value}"));
            }

            var win32 = new Win32Exception(this.LastError.Value);
            throw new Win32Exception(
                this.LastError.Value,
                string.Join(Environment.NewLine,
                    $"{this.MemberName} failed.",
                    $"ReturnValue: {this.Value}",
                    $"LastError: {this.LastError.Value}",
                    $"Message: {win32.Message}"));
        }

        return this;
    }

    /// <summary>
    /// No-op that lets the caller signal it's deliberately ignoring a possible failure.
    /// </summary>
    public Win32Result<T> IgnoreFailure()
        => this;

    /// <summary>
    /// Method form of <see cref="Value"/>, so the end of a fluent chain reads
    /// as an action (<c>.ThrowIfFailed().GetValue()</c>) rather than trailing
    /// off into a property access.
    /// </summary>
    public T GetValue()
        => this.Value;
}
