// Copyright (c) Microsoft Corporation
// The Microsoft Corporation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

// <auto-generated/>
#nullable enable

namespace MouseJump.Common.Win32Gen;

/// <summary>
/// Carries a raw Win32 api return value while its <see cref="Win32Result{T}"/>
/// is being built up fluently (success rule, last error, ...). A struct so
/// the build-up doesn't allocate, since these are expected to sit on hot paths.
/// </summary>
internal readonly struct Win32ReturnCode<T>
{
    internal Win32ReturnCode(T value, bool success, int? lastError, string memberName)
    {
        this.Value = value;
        this.Success = success;
        this.LastError = lastError;
        this.MemberName = memberName;
    }

    public T Value { get; }

    public bool Success { get; }

    public bool Failure => !this.Success;

    public int? LastError { get; }

    public string MemberName { get; }

    /// <summary>
    /// Same data <see cref="Win32ReturnCode.AsWin32Result{T}"/> copies across
    /// explicitly - lets a wrapper's fluent chain end on <c>.WithLastError()</c>
    /// (or a <c>SuccessIsXxx()</c>/<c>AlwaysSucceeds()</c> call directly) and
    /// still satisfy a method declared to return <see cref="Win32Result{T}"/>,
    /// without an explicit <c>.AsWin32Result()</c> at every call site.
    /// </summary>
    public static implicit operator Win32Result<T>(Win32ReturnCode<T> code)
        => new(code.Value, code.Success, code.LastError, code.MemberName);
}
