// Copyright (c) Microsoft Corporation
// The Microsoft Corporation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

// <auto-generated/>
#nullable enable

namespace MouseJump.Common.Win32Gen;

using System.Runtime.CompilerServices;

using Windows.Win32.Graphics.Gdi;

internal static partial class Win32ReturnCode
{
    // see the comment in Win32ReturnCode_HWND.cs - each CsWin32 handle
    // struct needs its own overload here.
    internal static Win32ReturnCode<HMONITOR> SuccessIsNotNull(
        this HMONITOR result,
        [CallerMemberName] string memberName = "")
        => new(result, !result.IsNull, lastError: null, memberName);
}
