<!-- Copyright (c) Microsoft Corporation. All rights reserved. -->
<!-- Licensed under the MIT License. See LICENSE file in the project root for license information. -->
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(RepoRoot)src\Common.Dotnet.CsWinRT.props" />
  <Import Project="$(RepoRoot)src\Common.SelfContained.props" />
  <Import Project="$(RepoRoot)src\Common.Dotnet.AotCompatibility.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>LightSwitch.Cli</RootNamespace>
    <AssemblyName>PowerToys.LightSwitch.Cli</AssemblyName>
    <ApplicationIcon>..\LightSwitchService\LightSwitch.ico</ApplicationIcon>
    <Platforms>x64;ARM64</Platforms>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <OutputPath>$(RepoRoot)$(Platform)\$(Configuration)\</OutputPath>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishAot>true</PublishAot>
    <PublishSingleFile>false</PublishSingleFile>
    <DisableRuntimeMarshalling>false</DisableRuntimeMarshalling>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="*.log" />
    <None Remove="*.binlog" />
    <InternalsVisibleTo Include="LightSwitch.Cli.UnitTests" />
    <FrameworkReference Include="Microsoft.WindowsDesktop.App" />
    <PackageReference Include="System.CommandLine" />
    <ProjectReference Include="$(RepoRoot)src\common\ManagedCommon\ManagedCommon.csproj" />
  </ItemGroup>
</Project>
