//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.PowerToys.Run.Plugin.Everything.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Community.PowerToys.Run.Plugin.Everything.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to set text in clipboard 的本地化字符串。
        /// </summary>
        internal static string Community_plugin_everything_clipboard_failed {
            get {
                return ResourceManager.GetString("Community_plugin_everything_clipboard_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied 的本地化字符串。
        /// </summary>
        internal static string Community_plugin_everything_copied {
            get {
                return ResourceManager.GetString("Community_plugin_everything_copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy path (Ctrl+C) 的本地化字符串。
        /// </summary>
        internal static string Community_plugin_everything_copy_path {
            get {
                return ResourceManager.GetString("Community_plugin_everything_copy_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to open folder at 的本地化字符串。
        /// </summary>
        internal static string Community_plugin_everything_folder_open_failed {
            get {
                return ResourceManager.GetString("Community_plugin_everything_folder_open_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything is not running 的本地化字符串。
        /// </summary>
        internal static string Community_plugin_everything_is_not_running {
            get {
                return ResourceManager.GetString("Community_plugin_everything_is_not_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open containing folder (Ctrl+Shift+E) 的本地化字符串。
        /// </summary>
        internal static string Community_plugin_everything_open_containing_folder {
            get {
                return ResourceManager.GetString("Community_plugin_everything_open_containing_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open path in console (Ctrl+Shift+C) 的本地化字符串。
        /// </summary>
        internal static string Community_plugin_everything_open_in_console {
            get {
                return ResourceManager.GetString("Community_plugin_everything_open_in_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Everything to search files 的本地化字符串。
        /// </summary>
        internal static string Community_plugin_everything_plugin_description {
            get {
                return ResourceManager.GetString("Community_plugin_everything_plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything Search 的本地化字符串。
        /// </summary>
        internal static string Community_plugin_everything_plugin_name {
            get {
                return ResourceManager.GetString("Community_plugin_everything_plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything query error 的本地化字符串。
        /// </summary>
        internal static string Community_plugin_everything_query_error {
            get {
                return ResourceManager.GetString("Community_plugin_everything_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run as administrator (Ctrl+Shift+Enter) 的本地化字符串。
        /// </summary>
        internal static string Community_plugin_everything_run_as_administrator {
            get {
                return ResourceManager.GetString("Community_plugin_everything_run_as_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything is not found on this computer 的本地化字符串。
        /// </summary>
        internal static string everything_notfound_warning {
            get {
                return ResourceManager.GetString("everything_notfound_warning", resourceCulture);
            }
        }
    }
}
