//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Plugin.Program.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Plugin.Program.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string powertoys_run_plugin_program_file_name {
            get {
                return ResourceManager.GetString("powertoys_run_plugin_program_file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string powertoys_run_plugin_program_file_path {
            get {
                return ResourceManager.GetString("powertoys_run_plugin_program_file_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string powertoys_run_plugin_program_folder_type {
            get {
                return ResourceManager.GetString("powertoys_run_plugin_program_folder_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string powertoys_run_plugin_program_generic_file_type {
            get {
                return ResourceManager.GetString("powertoys_run_plugin_program_generic_file_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet shortcut application.
        /// </summary>
        public static string powertoys_run_plugin_program_internet_shortcut_application {
            get {
                return ResourceManager.GetString("powertoys_run_plugin_program_internet_shortcut_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaged application.
        /// </summary>
        public static string powertoys_run_plugin_program_packaged_application {
            get {
                return ResourceManager.GetString("powertoys_run_plugin_program_packaged_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run command.
        /// </summary>
        public static string powertoys_run_plugin_program_run_command {
            get {
                return ResourceManager.GetString("powertoys_run_plugin_program_run_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web application.
        /// </summary>
        public static string powertoys_run_plugin_program_web_application {
            get {
                return ResourceManager.GetString("powertoys_run_plugin_program_web_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string powertoys_run_plugin_program_win32_application {
            get {
                return ResourceManager.GetString("powertoys_run_plugin_program_win32_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string wox_plugin_program_add {
            get {
                return ResourceManager.GetString("wox_plugin_program_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All programs.
        /// </summary>
        public static string wox_plugin_program_all_programs {
            get {
                return ResourceManager.GetString("wox_plugin_program_all_programs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string wox_plugin_program_browse {
            get {
                return ResourceManager.GetString("wox_plugin_program_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string wox_plugin_program_delete {
            get {
                return ResourceManager.GetString("wox_plugin_program_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected program sources?.
        /// </summary>
        public static string wox_plugin_program_delete_program_source {
            get {
                return ResourceManager.GetString("wox_plugin_program_delete_program_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory:.
        /// </summary>
        public static string wox_plugin_program_directory {
            get {
                return ResourceManager.GetString("wox_plugin_program_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string wox_plugin_program_disable {
            get {
                return ResourceManager.GetString("wox_plugin_program_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string wox_plugin_program_disable_dlgtitle_success {
            get {
                return ResourceManager.GetString("wox_plugin_program_disable_dlgtitle_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully disabled this program from displaying in your query.
        /// </summary>
        public static string wox_plugin_program_disable_dlgtitle_success_message {
            get {
                return ResourceManager.GetString("wox_plugin_program_disable_dlgtitle_success_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable this program from displaying.
        /// </summary>
        public static string wox_plugin_program_disable_program {
            get {
                return ResourceManager.GetString("wox_plugin_program_disable_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string wox_plugin_program_edit {
            get {
                return ResourceManager.GetString("wox_plugin_program_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File suffixes:.
        /// </summary>
        public static string wox_plugin_program_file_suffixes {
            get {
                return ResourceManager.GetString("wox_plugin_program_file_suffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index registry.
        /// </summary>
        public static string wox_plugin_program_index_registry {
            get {
                return ResourceManager.GetString("wox_plugin_program_index_registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index start menu.
        /// </summary>
        public static string wox_plugin_program_index_start {
            get {
                return ResourceManager.GetString("wox_plugin_program_index_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexing.
        /// </summary>
        public static string wox_plugin_program_indexing {
            get {
                return ResourceManager.GetString("wox_plugin_program_indexing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Path.
        /// </summary>
        public static string wox_plugin_program_invalid_path {
            get {
                return ResourceManager.GetString("wox_plugin_program_invalid_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string wox_plugin_program_location {
            get {
                return ResourceManager.GetString("wox_plugin_program_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max depth.
        /// </summary>
        public static string wox_plugin_program_max_depth_header {
            get {
                return ResourceManager.GetString("wox_plugin_program_max_depth_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum search depth (-1 is unlimited):.
        /// </summary>
        public static string wox_plugin_program_max_search_depth {
            get {
                return ResourceManager.GetString("wox_plugin_program_max_search_depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wox will only index files that end with the following suffixes:.
        /// </summary>
        public static string wox_plugin_program_only_index_tip {
            get {
                return ResourceManager.GetString("wox_plugin_program_only_index_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open containing folder (Ctrl+Shift+E).
        /// </summary>
        public static string wox_plugin_program_open_containing_folder {
            get {
                return ResourceManager.GetString("wox_plugin_program_open_containing_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open path in console (Ctrl+Shift+C).
        /// </summary>
        public static string wox_plugin_program_open_in_console {
            get {
                return ResourceManager.GetString("wox_plugin_program_open_in_console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a program source.
        /// </summary>
        public static string wox_plugin_program_pls_select_program_source {
            get {
                return ResourceManager.GetString("wox_plugin_program_pls_select_program_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search programs in Wox.
        /// </summary>
        public static string wox_plugin_program_plugin_description {
            get {
                return ResourceManager.GetString("wox_plugin_program_plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string wox_plugin_program_plugin_name {
            get {
                return ResourceManager.GetString("wox_plugin_program_plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reindex.
        /// </summary>
        public static string wox_plugin_program_reindex {
            get {
                return ResourceManager.GetString("wox_plugin_program_reindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as administrator (Ctrl+Shift+Enter).
        /// </summary>
        public static string wox_plugin_program_run_as_administrator {
            get {
                return ResourceManager.GetString("wox_plugin_program_run_as_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as different user.
        /// </summary>
        public static string wox_plugin_program_run_as_different_user {
            get {
                return ResourceManager.GetString("wox_plugin_program_run_as_different_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Each suffix should split by &apos;;&apos; ).
        /// </summary>
        public static string wox_plugin_program_split_by_tip {
            get {
                return ResourceManager.GetString("wox_plugin_program_split_by_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File suffixes.
        /// </summary>
        public static string wox_plugin_program_suffixes {
            get {
                return ResourceManager.GetString("wox_plugin_program_suffixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File suffixes can&apos;t be empty.
        /// </summary>
        public static string wox_plugin_program_suffixes_cannot_empty {
            get {
                return ResourceManager.GetString("wox_plugin_program_suffixes_cannot_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffixes.
        /// </summary>
        public static string wox_plugin_program_suffixes_header {
            get {
                return ResourceManager.GetString("wox_plugin_program_suffixes_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string wox_plugin_program_update {
            get {
                return ResourceManager.GetString("wox_plugin_program_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated file suffixes.
        /// </summary>
        public static string wox_plugin_program_update_file_suffixes {
            get {
                return ResourceManager.GetString("wox_plugin_program_update_file_suffixes", resourceCulture);
            }
        }
    }
}
