#pragma once
#define NOMINMAX
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <windowsx.h>
#include <ShellScalingApi.h>
#include <dwmapi.h>
#include <stdint.h>
#include <atomic>
#include <thread>
#include <chrono>
#include <optional>
#include <string>
#include <memory>
#include <algorithm>
#include <cmath>
#include <common/SettingsAPI/settings_objects.h>
#include <interface/powertoy_module_interface.h>
#include <common/logger/logger.h>
#include <common/utils/logger_helper.h>
