#pragma once

#define IDI_APP_ICON 100
#define IDS_APP_TITLE 101
#define IDS_DISPLAY_SELECTOR_TITLE 102
#define IDS_DISPLAY_SELECTOR_INSTRUCTION 103
#define IDS_DISPLAY_SELECTOR_DESCRIPTION 104
#define IDS_PRIMARY_DISPLAY 105
#define IDS_CAPTURE_ERROR 106
#define IDS_DISPLAY_LABEL 107
#define IDS_CANCEL 108
