
namespace CmdPalKeyboardService
{
    [version(1.0), uuid(78ab07cd-e128-4e73-86aa-e48e6b6d01ff)] delegate void ProcessCommand(String id);

    [default_interface] runtimeclass KeyboardListener {
        KeyboardListener();
        void Start();
        void Stop();

        void SetHotkeyAction(Boolean win, Boolean ctrl, Boolean shift, Boolean alt, UInt8 key, String id);
        void ClearHotkey(String id);
        void ClearHotkeys();
        void SetProcessCommand(ProcessCommand processCommand);
    }
}
