#pragma once

enum class SettingId
{
    ShiftDrag = 0,
    MouseSwitch,
    MouseMiddleClickSpanningMultipleZones,
    OverrideSnapHotkeys,
    MoveWindowAcrossMonitors,
    MoveWindowsBasedOnPosition,
    OverlappingZonesAlgorithm,
    DisplayOrWorkAreaChangeMoveWindows,
    ZoneSetChangeMoveWindows,
    AppLastZoneMoveWindows,
    OpenWindowOnActiveMonitor,
    RestoreWindowSize,
    QuickLayoutSwitch,
    FlashZonesOnQuickSwitch,
    LaunchEditorOnScreenWhereCursorPlaced,
    ShowOnAllMonitors,
    SpanZonesAcrossMonitors,
    MakeDraggedWindowsTransparent,
    ZoneHighlightColor,
    ZoneHighlightOpacity,
    ZoneBorderColor,
    ZoneColor,
    ZoneNumberColor,
    SystemTheme,
    ShowZoneNumber,
    EditorHotkey,
    WindowSwitching,
    NextTabHotkey,
    PrevTabHotkey,
    ExcludedApps,
    AllowSnapChildWindows,
    DisableRoundCornersOnSnapping,
};