namespace FileLocksmithGUI
{
    [default_interface]
    runtimeclass ProcessEntry : Microsoft.UI.Xaml.Controls.UserControl
    {
        ProcessEntry(String process, UInt32 pid, UInt64 num_files);
        UInt32 Pid();
    }
}
