//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorPowerExtension.Properties
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonitorPowerExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string provider_display_name => ResourceManager.GetString("provider_display_name", resourceCulture);

        public static string provider_subtitle => ResourceManager.GetString("provider_subtitle", resourceCulture);

        public static string page_title => ResourceManager.GetString("page_title", resourceCulture);

        public static string switch_to_external_title => ResourceManager.GetString("switch_to_external_title", resourceCulture);

        public static string switch_to_external_subtitle => ResourceManager.GetString("switch_to_external_subtitle", resourceCulture);

        public static string switch_to_internal_title => ResourceManager.GetString("switch_to_internal_title", resourceCulture);

        public static string switch_to_internal_subtitle => ResourceManager.GetString("switch_to_internal_subtitle", resourceCulture);

        public static string choose_monitors_title => ResourceManager.GetString("choose_monitors_title", resourceCulture);

        public static string apply_profile_title => ResourceManager.GetString("apply_profile_title", resourceCulture);

        public static string apply_profile_subtitle => ResourceManager.GetString("apply_profile_subtitle", resourceCulture);

        public static string restore_state_title => ResourceManager.GetString("restore_state_title", resourceCulture);

        public static string restore_state_subtitle => ResourceManager.GetString("restore_state_subtitle", resourceCulture);

        public static string apply_selection => ResourceManager.GetString("apply_selection", resourceCulture);

        public static string apply_selection_subtitle => ResourceManager.GetString("apply_selection_subtitle", resourceCulture);

        public static string will_stay_on => ResourceManager.GetString("will_stay_on", resourceCulture);

        public static string will_turn_off => ResourceManager.GetString("will_turn_off", resourceCulture);

        public static string cannot_disable_all => ResourceManager.GetString("cannot_disable_all", resourceCulture);

        public static string no_active_displays => ResourceManager.GetString("no_active_displays", resourceCulture);

        public static string display_state_restored => ResourceManager.GetString("display_state_restored", resourceCulture);

        public static string no_saved_state => ResourceManager.GetString("no_saved_state", resourceCulture);

        public static string display_label => ResourceManager.GetString("display_label", resourceCulture);

        public static string unknown_display => ResourceManager.GetString("unknown_display", resourceCulture);

        public static string displays_active => ResourceManager.GetString("displays_active", resourceCulture);

        public static string external_display => ResourceManager.GetString("external_display", resourceCulture);

        public static string internal_display => ResourceManager.GetString("internal_display", resourceCulture);

        public static string switch_to_external_command_name => ResourceManager.GetString("switch_to_external_command_name", resourceCulture);

        public static string switch_to_internal_command_name => ResourceManager.GetString("switch_to_internal_command_name", resourceCulture);

        public static string choose_monitors_command_name => ResourceManager.GetString("choose_monitors_command_name", resourceCulture);

        public static string switched_display_topology => ResourceManager.GetString("switched_display_topology", resourceCulture);

        public static string activated_displays_format => ResourceManager.GetString("activated_displays_format", resourceCulture);

        public static string profile_saved_format => ResourceManager.GetString("profile_saved_format", resourceCulture);

        public static string error_format => ResourceManager.GetString("error_format", resourceCulture);

        public static string error_prefix => ResourceManager.GetString("error_prefix", resourceCulture);

        public static string error_saved_state_no_paths => ResourceManager.GetString("error_saved_state_no_paths", resourceCulture);

        public static string error_no_displays_selected => ResourceManager.GetString("error_no_displays_selected", resourceCulture);

        public static string error_no_displays_connected => ResourceManager.GetString("error_no_displays_connected", resourceCulture);

        public static string error_no_active_monitors_remaining => ResourceManager.GetString("error_no_active_monitors_remaining", resourceCulture);

        public static string error_no_matching_paths => ResourceManager.GetString("error_no_matching_paths", resourceCulture);

        public static string error_no_active_to_save => ResourceManager.GetString("error_no_active_to_save", resourceCulture);

        public static string error_profile_not_found => ResourceManager.GetString("error_profile_not_found", resourceCulture);

        public static string error_profile_empty => ResourceManager.GetString("error_profile_empty", resourceCulture);

        public static string error_profile_layout_invalid => ResourceManager.GetString("error_profile_layout_invalid", resourceCulture);

        public static string restore_failed_format => ResourceManager.GetString("restore_failed_format", resourceCulture);

        public static string press_esc_to_undo => ResourceManager.GetString("press_esc_to_undo", resourceCulture);

        public static string save_profile_title => ResourceManager.GetString("save_profile_title", resourceCulture);

        public static string save_profile_subtitle => ResourceManager.GetString("save_profile_subtitle", resourceCulture);

        public static string profile_saved => ResourceManager.GetString("profile_saved", resourceCulture);

        public static string profile_name_label => ResourceManager.GetString("profile_name_label", resourceCulture);

        public static string profile_name_placeholder => ResourceManager.GetString("profile_name_placeholder", resourceCulture);

        public static string select_monitors_label => ResourceManager.GetString("select_monitors_label", resourceCulture);

        public static string save_profile_button => ResourceManager.GetString("save_profile_button", resourceCulture);

        public static string profile_name_required => ResourceManager.GetString("profile_name_required", resourceCulture);

        public static string profile_no_monitors => ResourceManager.GetString("profile_no_monitors", resourceCulture);

        public static string create_profile_page_title => ResourceManager.GetString("create_profile_page_title", resourceCulture);

        public static string apply_profile_status => ResourceManager.GetString("apply_profile_status", resourceCulture);

        public static string profile_applied => ResourceManager.GetString("profile_applied", resourceCulture);

        public static string delete_profile_title => ResourceManager.GetString("delete_profile_title", resourceCulture);

        public static string profile_deleted => ResourceManager.GetString("profile_deleted", resourceCulture);

        public static string edit_profile_title => ResourceManager.GetString("edit_profile_title", resourceCulture);

        public static string edit_profile_page_title => ResourceManager.GetString("edit_profile_page_title", resourceCulture);
    }
}
