//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.PowerToys.Run.Plugin.ValueGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Community.PowerToys.Run.Plugin.ValueGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy failed.
        /// </summary>
        public static string copy_failed {
            get {
                return ResourceManager.GetString("copy_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} to clipboard.
        /// </summary>
        public static string copy_to_clipboard {
            get {
                return ResourceManager.GetString("copy_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Generator Error.
        /// </summary>
        public static string error_title {
            get {
                return ResourceManager.GetString("error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode a string with Base64.
        /// </summary>
        public static string generator_description_base64 {
            get {
                return ResourceManager.GetString("generator_description_base64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode a string with Base64.
        /// </summary>
        public static string generator_description_base64d {
            get {
                return ResourceManager.GetString("generator_description_base64d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape a data string.
        /// </summary>
        public static string generator_description_esc_data {
            get {
                return ResourceManager.GetString("generator_description_esc_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape a single hex character.
        /// </summary>
        public static string generator_description_esc_hex {
            get {
                return ResourceManager.GetString("generator_description_esc_hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash a string with {0}.
        /// </summary>
        public static string generator_description_hash {
            get {
                return ResourceManager.GetString("generator_description_hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unescape a data string.
        /// </summary>
        public static string generator_description_uesc_data {
            get {
                return ResourceManager.GetString("generator_description_uesc_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unescape a single hex character.
        /// </summary>
        public static string generator_description_uesc_hex {
            get {
                return ResourceManager.GetString("generator_description_uesc_hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode a URL.
        /// </summary>
        public static string generator_description_url {
            get {
                return ResourceManager.GetString("generator_description_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode a URL.
        /// </summary>
        public static string generator_description_urld {
            get {
                return ResourceManager.GetString("generator_description_urld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a random UUID.
        /// </summary>
        public static string generator_description_uuid {
            get {
                return ResourceManager.GetString("generator_description_uuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a version 1: Time based UUID.
        /// </summary>
        public static string generator_description_uuidv1 {
            get {
                return ResourceManager.GetString("generator_description_uuidv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a version 3 (MD5): Namespace and name based UUID.
        /// </summary>
        public static string generator_description_uuidv3 {
            get {
                return ResourceManager.GetString("generator_description_uuidv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a version 4: Randomly generated UUID.
        /// </summary>
        public static string generator_description_uuidv4 {
            get {
                return ResourceManager.GetString("generator_description_uuidv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a version 5 (SHA1): Namespace and name based UUID.
        /// </summary>
        public static string generator_description_uuidv5 {
            get {
                return ResourceManager.GetString("generator_description_uuidv5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a version 7: Time-ordered randomly generated UUID.
        /// </summary>
        public static string generator_description_uuidv7 {
            get {
                return ResourceManager.GetString("generator_description_uuidv7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your input.
        /// </summary>
        public static string generator_description_your_input {
            get {
                return ResourceManager.GetString("generator_description_your_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: {0}.
        /// </summary>
        public static string generator_example {
            get {
                return ResourceManager.GetString("generator_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates hashes and generate values.
        /// </summary>
        public static string plugin_description {
            get {
                return ResourceManager.GetString("plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Generator.
        /// </summary>
        public static string plugin_name {
            get {
                return ResourceManager.GetString("plugin_name", resourceCulture);
            }
        }
    }
}
