//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by KeyboardManager.rc

//////////////////////////////
// Non-localizable

#define FILE_DESCRIPTION "PowerToys KeyboardManager"
#define INTERNAL_NAME "KeyboardManager"
#define ORIGINAL_FILENAME "KeyboardManager.dll"

// Non-localizable
//////////////////////////////

#define IDS_SETTINGS_DESCRIPTION 101
#define IDS_KEYBOARDMANAGER 102
#define IDS_KEYBOARDMANAGER_ICON 103
#define IDS_CREATEWINDOWFAILED_ERRORMESSAGE 104
#define IDS_CREATEWINDOWFAILED_ERRORTITLE 105
#define IDS_REGISTERCLASSFAILED_ERRORMESSAGE 106
#define IDS_REGISTERCLASSFAILED_ERRORTITLE 107
#define IDS_EDITKEYBOARD_WINDOWNAME 108
#define IDS_EDITSHORTCUTS_WINDOWNAME 109
#define IDS_CANCEL_BUTTON 110
#define IDS_OK_BUTTON 111
#define IDS_CONTINUE_BUTTON 112
#define IDS_EDITKEYBOARD_SOURCEHEADER 113
#define IDS_EDITKEYBOARD_TARGETHEADER 114
#define IDS_EDITSHORTCUTS_SOURCEHEADER 115
#define IDS_EDITSHORTCUTS_TARGETHEADER 116
#define IDS_EDITSHORTCUTS_TARGETAPPHEADER 117
#define IDS_EDITKEYBOARD_ORPHANEDDIALOGTITLE 118
#define IDS_EDITKEYBOARD_PARTIALCONFIRMATIONDIALOGTITLE 119
#define IDS_EDITSHORTCUTS_PARTIALCONFIRMATIONDIALOGTITLE 120
#define IDS_EDITKEYBOARD_INFO 121
#define IDS_EDITKEYBOARD_INFOEXAMPLE 122
#define IDS_EDITSHORTCUTS_INFO 123
#define IDS_EDITSHORTCUTS_INFOEXAMPLE 124
#define IDS_TYPE_BUTTON 125
#define IDS_TYPEKEY_TITLE 126
#define IDS_TYPESHORTCUT_TITLE 127
#define IDS_TYPEKEY_HEADER 128
#define IDS_TYPESHORTCUT_HEADER 129
#define IDS_TYPE_HOLDENTER 130
#define IDS_TYPE_HOLDESC 131
#define IDS_EDITSHORTCUTS_ALLAPPS 132
#define IDS_ERRORMESSAGE_REMAPSUCCESSFUL 133
#define IDS_ERRORMESSAGE_REMAPUNSUCCESSFUL 134
#define IDS_ERRORMESSAGE_SAMEKEYPREVIOUSLYMAPPED 135
#define IDS_ERRORMESSAGE_MAPPEDTOSAMEKEY 136
#define IDS_ERRORMESSAGE_CONFLICTINGMODIFIERKEY 137
#define IDS_ERRORMESSAGE_SAMESHORTCUTPREVIOUSLYMAPPED 138
#define IDS_ERRORMESSAGE_MAPTOSAMESHORTCUT 139
#define IDS_ERRORMESSAGE_CONFLICTINGMODIFIERSHORTCUT 140
#define IDS_ERRORMESSAGE_WINL 141
#define IDS_ERRORMESSAGE_CTRLALTDEL 142
#define IDS_ERRORMESSAGE_SAVEFAILED 143
#define IDS_ERRORMESSAGE_SHORTCUTSTARTWITHMODIFIER 144
#define IDS_ERRORMESSAGE_SHORTCUTNOREPEATEDMODIFIER 145
#define IDS_ERRORMESSAGE_SHORTCUTATLEAST2KEYS 146
#define IDS_ERRORMESSAGE_SHORTCUTONEACTIONKEY 147
#define IDS_ERRORMESSAGE_SHORTCUTMAXONEACTIONKEY 148
#define IDS_ERRORMESSAGE_MAXSHORTCUTSIZE 149
#define IDS_ERRORMESSAGE_DEFAULT 150
