#pragma once
#define WIN32_LEAN_AND_MEAN
#include <Windows.h>
#include <winrt/base.h>
#include <string>
#include <vector>
#include <algorithm>
#include <stdlib.h>
#include <ProjectTelemetry.h>