namespace PowerToys
{
    namespace MeasureToolCore
    {
        struct Point
        {
            Int32 X;
            Int32 Y;
        };

        delegate void ToolSessionCompleted();

        [default_interface]
        runtimeclass Core
        {
            Core();
            void SetToolCompletionEvent(event ToolSessionCompleted completionTrigger);
            void StartMeasureTool(Boolean horizontal, Boolean vertical);
            void StartBoundsTool();

            Point GetCursorPosition();
        }
    }
}
