namespace PowerToys
{
    namespace MeasureToolCore
    {
        struct Point
        {
            Int32 X;
            Int32 Y;
        };

        delegate void ToolSessionCompleted();

        [default_interface]
        runtimeclass Core : Windows.Foundation.IClosable
        {
            Core();
            void SetToolCompletionEvent(event ToolSessionCompleted completionTrigger);
            void StartMeasureTool(Boolean horizontal, Boolean vertical);
            void StartBoundsTool();
            void ResetState();

            void SetToolbarBoundingBox(Int32 fromX, Int32 fromY, Int32 toX, Int32 toY);
            Single GetDPIScaleForWindow(Int64 windowHandle);
        }
    }
}
