//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CmdPal.Ext.Indexer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CmdPal.Ext.Indexer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Indexer_Command_Browse {
            get {
                return ResourceManager.GetString("Indexer_Command_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path.
        /// </summary>
        internal static string Indexer_Command_CopyPath {
            get {
                return ResourceManager.GetString("Indexer_Command_CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Indexer_Command_OpenFile {
            get {
                return ResourceManager.GetString("Indexer_Command_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open path in console.
        /// </summary>
        internal static string Indexer_Command_OpenPathInConsole {
            get {
                return ResourceManager.GetString("Indexer_Command_OpenPathInConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Indexer_Command_OpenProperties {
            get {
                return ResourceManager.GetString("Indexer_Command_OpenProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with.
        /// </summary>
        internal static string Indexer_Command_OpenWith {
            get {
                return ResourceManager.GetString("Indexer_Command_OpenWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in folder.
        /// </summary>
        internal static string Indexer_Command_ShowInFolder {
            get {
                return ResourceManager.GetString("Indexer_Command_ShowInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file doesn&apos;t exist.
        /// </summary>
        internal static string Indexer_File_Does_Not_Exist {
            get {
                return ResourceManager.GetString("Indexer_File_Does_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a file, not a folder.
        /// </summary>
        internal static string Indexer_File_Is_File_Not_Folder {
            get {
                return ResourceManager.GetString("Indexer_File_Is_File_Not_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find file from path.
        /// </summary>
        internal static string Indexer_Find_Path_fallback_display_title {
            get {
                return ResourceManager.GetString("Indexer_Find_Path_fallback_display_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder is empty.
        /// </summary>
        internal static string Indexer_Folder_Is_Empty {
            get {
                return ResourceManager.GetString("Indexer_Folder_Is_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for files and folders....
        /// </summary>
        internal static string Indexer_PlaceholderText {
            get {
                return ResourceManager.GetString("Indexer_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search files on this device.
        /// </summary>
        internal static string Indexer_Subtitle {
            get {
                return ResourceManager.GetString("Indexer_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search files.
        /// </summary>
        internal static string Indexer_Title {
            get {
                return ResourceManager.GetString("Indexer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File search.
        /// </summary>
        internal static string IndexerCommandsProvider_DisplayName {
            get {
                return ResourceManager.GetString("IndexerCommandsProvider_DisplayName", resourceCulture);
            }
        }
    }
}
