//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CmdPal.Ext.Indexer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CmdPal.Ext.Indexer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions....
        /// </summary>
        internal static string Indexer_Command_Actions {
            get {
                return ResourceManager.GetString("Indexer_Command_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Indexer_Command_Browse {
            get {
                return ResourceManager.GetString("Indexer_Command_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path.
        /// </summary>
        internal static string Indexer_Command_CopyPath {
            get {
                return ResourceManager.GetString("Indexer_Command_CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Indexer_Command_OpenFile {
            get {
                return ResourceManager.GetString("Indexer_Command_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Windows Search settings.
        /// </summary>
        internal static string Indexer_Command_OpenIndexerSettings {
            get {
                return ResourceManager.GetString("Indexer_Command_OpenIndexerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open path in console.
        /// </summary>
        internal static string Indexer_Command_OpenPathInConsole {
            get {
                return ResourceManager.GetString("Indexer_Command_OpenPathInConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Indexer_Command_OpenProperties {
            get {
                return ResourceManager.GetString("Indexer_Command_OpenProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with.
        /// </summary>
        internal static string Indexer_Command_OpenWith {
            get {
                return ResourceManager.GetString("Indexer_Command_OpenWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search all files.
        /// </summary>
        internal static string Indexer_Command_SearchAllFiles {
            get {
                return ResourceManager.GetString("Indexer_Command_SearchAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in folder.
        /// </summary>
        internal static string Indexer_Command_ShowInFolder {
            get {
                return ResourceManager.GetString("Indexer_Command_ShowInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for &quot;{0}&quot; in files.
        /// </summary>
        internal static string Indexer_fallback_searchPage_title {
            get {
                return ResourceManager.GetString("Indexer_fallback_searchPage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file doesn&apos;t exist.
        /// </summary>
        internal static string Indexer_File_Does_Not_Exist {
            get {
                return ResourceManager.GetString("Indexer_File_Does_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a file, not a folder.
        /// </summary>
        internal static string Indexer_File_Is_File_Not_Folder {
            get {
                return ResourceManager.GetString("Indexer_File_Is_File_Not_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files and folders.
        /// </summary>
        internal static string Indexer_Filter_All {
            get {
                return ResourceManager.GetString("Indexer_Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string Indexer_Filter_Files_Only {
            get {
                return ResourceManager.GetString("Indexer_Filter_Files_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        internal static string Indexer_Filter_Folders_Only {
            get {
                return ResourceManager.GetString("Indexer_Filter_Folders_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find file from path.
        /// </summary>
        internal static string Indexer_Find_Path_fallback_display_title {
            get {
                return ResourceManager.GetString("Indexer_Find_Path_fallback_display_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder is empty.
        /// </summary>
        internal static string Indexer_Folder_Is_Empty {
            get {
                return ResourceManager.GetString("Indexer_Folder_Is_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found.
        /// </summary>
        internal static string Indexer_NoResultsMessage {
            get {
                return ResourceManager.GetString("Indexer_NoResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing was found in the indexed locations.
        ///You can try searching all files on this PC or adjust your indexing settings..
        /// </summary>
        internal static string Indexer_NoResultsMessageTip {
            get {
                return ResourceManager.GetString("Indexer_NoResultsMessageTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: Refine your search using filters, just like in File Explorer (e.g., type:directory)..
        /// </summary>
        internal static string Indexer_NoSearchQueryMessageTip {
            get {
                return ResourceManager.GetString("Indexer_NoSearchQueryMessageTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for files and folders....
        /// </summary>
        internal static string Indexer_PlaceholderText {
            get {
                return ResourceManager.GetString("Indexer_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on.
        /// </summary>
        internal static string Indexer_Settings_FallbackCommand_AlwaysOn {
            get {
                return ResourceManager.GetString("Indexer_Settings_FallbackCommand_AlwaysOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only when file path exist.
        /// </summary>
        internal static string Indexer_Settings_FallbackCommand_FilePathExist {
            get {
                return ResourceManager.GetString("Indexer_Settings_FallbackCommand_FilePathExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows file search results on the top-level search results.
        /// </summary>
        internal static string Indexer_Settings_FallbackCommand_Mode {
            get {
                return ResourceManager.GetString("Indexer_Settings_FallbackCommand_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always off.
        /// </summary>
        internal static string Indexer_Settings_FallbackCommand_Off {
            get {
                return ResourceManager.GetString("Indexer_Settings_FallbackCommand_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search files.
        /// </summary>
        internal static string Indexer_Title {
            get {
                return ResourceManager.GetString("Indexer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File search.
        /// </summary>
        internal static string IndexerCommandsProvider_DisplayName {
            get {
                return ResourceManager.GetString("IndexerCommandsProvider_DisplayName", resourceCulture);
            }
        }
    }
}
