#pragma once
#define WIN32_LEAN_AND_MEAN
#include <Windows.h>
#pragma push_macro("GetCurrentTime")
#undef GetCurrentTime
// include winrt headers with fix for "warning C4002: Too many arguments for function-like macro invocation GetCurrentTime"
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.Web.h>
#include <winrt/Windows.System.h>
#include <winrt/Windows.Web.UI.h>
#include <winrt/Windows.Web.UI.Interop.h>
#include <winrt/Windows.UI.Xaml.Controls.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Web.Http.h>
#include <winrt/Windows.Web.Http.Headers.h>
#include <winrt/Windows.Storage.h>
#include <winrt/Windows.Storage.Streams.h>
#pragma pop_macro("GetCurrentTime")
#include <strsafe.h>
#include <Shlwapi.h>
#include <ProjectTelemetry.h>
#include <thread>
