#define IDS_SETTING_DESCRIPTION_PRESS_TIME               101
#define IDS_SETTING_DESCRIPTION_OVERLAY_OPACITY          102
#define IDS_SETTING_DESCRIPTION_THEME                    103
#define IDS_SETTING_DESCRIPTION_THEME_LIGHT              104
#define IDS_SETTING_DESCRIPTION_THEME_DARK               105
#define IDS_SETTING_DESCRIPTION_THEME_SYSTEM             106
#define IDS_SETTINGS_DESCRIPTION                         107
#define IDS_SHORTCUT_GUIDE                               108
#define IDS_NO_ACTION                                    109
#define IDS_RESTORE                                      110
#define IDS_SNAP_RIGHT                                   111
#define IDS_SNAP_LEFT                                    112
#define IDS_SNAP_UPPER_RIGHT                             113
#define IDS_SNAP_UPPER_LEFT                              114
#define IDS_SNAP_LOWER_RIGHT                             115
#define IDS_SNAP_LOWER_LEFT                              116
#define IDS_MINIMIZE                                     117
#define IDS_MAXIMIZE                                     118
#define IDS_SETTING_DISPLAY_ON                           119
#define IDS_SETTING_DISPLAY_ON_MAIN_DISPLAY              120
#define IDS_SETTING_DISPLAY_ON_MOUSE_CURSOR_LOCATION     121
#define IDS_SETTING_DISPLAY_ON_ACTIVE_WINDOW_LOCATION    122
