<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\Common.Dotnet.CsWinRT.props" />
  <Import Project="..\..\..\Common.Dotnet.AotCompatibility.props" />

  <PropertyGroup>
    <AssemblyName>MonitorPower.Core</AssemblyName>
    <RootNamespace>MonitorPower</RootNamespace>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);SA1636</NoWarn>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Properties\Resources.resx">
      <LogicalName>MonitorPowerCore.Resources.resources</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Microsoft.CmdPal.UI</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>PowerToys.Settings</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Microsoft.CmdPal.Ext.MonitorPower.UnitTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
