/**
 * Raycast Icon enum compatibility stub.
 *
 * Maps Raycast's named icons to CmdPal's icon system. CmdPal uses
 * Segoe MDL2 Assets glyphs (Windows icon font) and emoji. We map
 * Raycast's icon enum values to the closest Segoe MDL2 glyph or emoji.
 *
 * Unknown icons fall back to a generic glyph (\uE8A5 = ActionCenter).
 */
/**
 * Raycast Icon enum — commonly used icon identifiers.
 * Values are Segoe MDL2 glyph codes or emoji that approximate the Raycast icon.
 */
export declare const Icon: {
    readonly AddPerson: "";
    readonly Airplane: "✈️";
    readonly AirplaneFilled: "✈️";
    readonly AirplaneLanding: "✈️";
    readonly AirplaneTakeoff: "✈️";
    readonly Alarm: "";
    readonly AppWindow: "";
    readonly AppWindowGrid2x2: "";
    readonly AppWindowGrid3x3: "";
    readonly ArrowClockwise: "";
    readonly ArrowCounterClockwise: "";
    readonly ArrowDown: "";
    readonly ArrowLeft: "";
    readonly ArrowRight: "";
    readonly ArrowUp: "";
    readonly ArrowNe: "";
    readonly ArrowRightCircle: "";
    readonly AtSymbol: "";
    readonly BankNote: "💵";
    readonly BarChart: "";
    readonly BathTub: "🛁";
    readonly BatteryCharging: "";
    readonly BatteryDisabled: "";
    readonly Bell: "";
    readonly BellDisabled: "";
    readonly Binoculars: "🔭";
    readonly Bird: "🐦";
    readonly BlankDocument: "";
    readonly Bluetooth: "";
    readonly Boat: "⛵";
    readonly Bold: "";
    readonly Bolt: "";
    readonly BoltDisabled: "";
    readonly Book: "";
    readonly Bookmark: "";
    readonly Box: "";
    readonly Brush: "";
    readonly Bug: "🐛";
    readonly Building: "";
    readonly BulletPoints: "";
    readonly BullsEye: "🎯";
    readonly Calendar: "";
    readonly Camera: "";
    readonly Car: "🚗";
    readonly Cart: "";
    readonly Cd: "💿";
    readonly Center: "";
    readonly Check: "";
    readonly Checkmark: "";
    readonly ChevronDown: "";
    readonly ChevronUp: "";
    readonly ChevronLeft: "";
    readonly ChevronRight: "";
    readonly Circle: "";
    readonly CircleEllipsis: "";
    readonly CircleFilled: "";
    readonly CircleProgress: "";
    readonly CircleProgress100: "";
    readonly CircleProgress25: "";
    readonly CircleProgress50: "";
    readonly CircleProgress75: "";
    readonly Clipboard: "";
    readonly Clock: "";
    readonly Cloud: "";
    readonly CloudLightning: "⛈️";
    readonly CloudRain: "🌧️";
    readonly CloudSnow: "❄️";
    readonly CloudSun: "⛅";
    readonly Code: "";
    readonly CodeBlock: "";
    readonly Cog: "";
    readonly Coin: "🪙";
    readonly Coins: "🪙";
    readonly CommandSymbol: "⌘";
    readonly Compass: "🧭";
    readonly ComputerChip: "";
    readonly Contrast: "";
    readonly CopyClipboard: "";
    readonly CreditCard: "💳";
    readonly Crop: "";
    readonly Crown: "👑";
    readonly Crypto: "₿";
    readonly DeleteDocument: "";
    readonly Desktop: "";
    readonly Diamond: "💎";
    readonly Dna: "🧬";
    readonly Document: "";
    readonly Dot: "•";
    readonly Download: "";
    readonly Duplicate: "";
    readonly EditShape: "";
    readonly Eject: "";
    readonly Ellipsis: "";
    readonly Emoji: "😀";
    readonly EmptyView: "";
    readonly Envelope: "";
    readonly Eraser: "";
    readonly ExclamationMark: "";
    readonly Eye: "";
    readonly EyeDisabled: "";
    readonly EyeDropper: "";
    readonly Female: "♀️";
    readonly FilmStrip: "🎞️";
    readonly Filter: "";
    readonly Finder: "";
    readonly Fingerprint: "";
    readonly Flag: "🏳️";
    readonly Folder: "";
    readonly Forward: "";
    readonly FullSignal: "";
    readonly GameController: "";
    readonly Gauge: "🔥";
    readonly Gear: "";
    readonly Gift: "🎁";
    readonly Glasses: "👓";
    readonly Globe: "";
    readonly Goal: "🎯";
    readonly Hammer: "🔨";
    readonly HardDrive: "";
    readonly Hashtag: "#";
    readonly Headphones: "";
    readonly Heart: "";
    readonly HeartDisabled: "";
    readonly Heartbeat: "💓";
    readonly Highlight: "";
    readonly Hourglass: "⏳";
    readonly House: "";
    readonly Image: "";
    readonly Important: "";
    readonly Info: "";
    readonly Italic: "";
    readonly Key: "";
    readonly Keyboard: "";
    readonly Layers: "";
    readonly Leaderboard: "🏆";
    readonly LevelMeter: "📊";
    readonly LightBulb: "";
    readonly LightBulbOff: "";
    readonly LineChart: "";
    readonly Link: "";
    readonly List: "";
    readonly Lock: "";
    readonly LockDisabled: "";
    readonly LockUnlocked: "";
    readonly Logout: "";
    readonly Lowercase: "";
    readonly MagnifyingGlass: "";
    readonly Male: "♂️";
    readonly Map: "🗺️";
    readonly Maximize: "";
    readonly Megaphone: "📢";
    readonly MemoryChip: "";
    readonly MemoryStick: "";
    readonly Message: "";
    readonly Microphone: "";
    readonly MicrophoneDisabled: "";
    readonly Minimize: "";
    readonly Minus: "";
    readonly MinusCircle: "";
    readonly Mobile: "";
    readonly Monitor: "";
    readonly Moon: "🌙";
    readonly Mountain: "⛰️";
    readonly Mouse: "";
    readonly Multiply: "";
    readonly Music: "";
    readonly Network: "";
    readonly NewDocument: "";
    readonly NewFolder: "";
    readonly Paperclip: "";
    readonly Paragraph: "";
    readonly Patch: "";
    readonly Pause: "";
    readonly PauseCircle: "";
    readonly Pencil: "";
    readonly People: "";
    readonly Person: "";
    readonly PersonCircle: "";
    readonly PersonLines: "";
    readonly Phone: "";
    readonly PhoneRinging: "";
    readonly Pin: "";
    readonly PinDisabled: "";
    readonly Play: "";
    readonly PlayCircle: "";
    readonly Plug: "";
    readonly Plus: "";
    readonly PlusCircle: "";
    readonly PlusMinusDivideMultiply: "";
    readonly PlusSquare: "";
    readonly PlusTopRightSquare: "";
    readonly Power: "";
    readonly Print: "";
    readonly QuestionMark: "";
    readonly QuestionMarkCircle: "";
    readonly QuoteBlock: "";
    readonly Raindrop: "💧";
    readonly Redo: "";
    readonly RemovePerson: "";
    readonly Repeat: "";
    readonly Reply: "";
    readonly Rewind: "";
    readonly RotateAntiClockwise: "";
    readonly RotateClockwise: "";
    readonly Rss: "📡";
    readonly Ruler: "📏";
    readonly SaveDocument: "";
    readonly Shield: "";
    readonly Shuffle: "";
    readonly Sidebar: "";
    readonly Signal0: "";
    readonly Signal1: "";
    readonly Signal2: "";
    readonly Signal3: "";
    readonly Snippets: "";
    readonly Snowflake: "❄️";
    readonly SoccerBall: "⚽";
    readonly Speaker: "";
    readonly SpeakerOff: "";
    readonly SpeechBubble: "";
    readonly SpeechBubbleActive: "";
    readonly SpeechBubbleImportant: "";
    readonly Star: "";
    readonly StarCircle: "";
    readonly StarDisabled: "";
    readonly Stop: "";
    readonly StopFilled: "";
    readonly Stopwatch: "⏱️";
    readonly Store: "";
    readonly Strikethrough: "";
    readonly Sun: "☀️";
    readonly Sunrise: "🌅";
    readonly Swatch: "";
    readonly Switch: "";
    readonly Syringe: "💉";
    readonly Tag: "";
    readonly Temperature: "🌡️";
    readonly Terminal: "";
    readonly Text: "";
    readonly TextCursor: "";
    readonly TextInput: "";
    readonly Thermometer: "🌡️";
    readonly Torch: "🔦";
    readonly Train: "🚂";
    readonly Trash: "";
    readonly Tray: "";
    readonly Tree: "🌲";
    readonly Trophy: "🏆";
    readonly TwoPeople: "";
    readonly Umbrella: "☂️";
    readonly Underline: "";
    readonly Undo: "";
    readonly Upload: "";
    readonly Uppercase: "";
    readonly Video: "";
    readonly Wallet: "";
    readonly Wand: "";
    readonly Warning: "";
    readonly Weights: "🏋️";
    readonly Wifi: "";
    readonly WifiDisabled: "";
    readonly Window: "";
    readonly Wrench: "";
    readonly XMarkCircle: "";
    readonly XMarkTopRightSquare: "";
};
export type IconEnum = typeof Icon;
export type IconKey = keyof IconEnum;
/**
 * Resolve a Raycast icon reference to a CmdPal-compatible icon string.
 * Handles both Icon enum values and custom image paths.
 */
export declare function resolveIcon(icon: unknown): string;
//# sourceMappingURL=icons.d.ts.map