namespace PowerToys
{
    namespace Interop
    {
        enum NamedPipePeerValidation
        {
            PowerToysPeer = 0,
            TrustedSignedProcess = 1,
        };

        [default_interface] static runtimeclass CommonManaged {
            static String GetProductVersion();
            static String GetProductVersionChannel();
            static String GetProductVersionSourceCommit();
            static Boolean AuthenticateNamedPipeServer(
                UInt64 pipeHandle,
                String expectedProcessName,
                String trustedDirectory,
                String referenceBinaryPath,
                NamedPipePeerValidation validation);
        }
    }
}