namespace PowerToys
{
    namespace Interop
    {
        [default_interface] static runtimeclass CommonManaged {
            static String GetProductVersion();
            static Windows.Foundation.Collections.IVector<String> GetAllActiveMicrophoneDeviceNames();
            static Windows.Foundation.Collections.IVector<String> GetAllVideoCaptureDeviceNames();
        }
    }
}