namespace PowerToys
{
    namespace Interop
    {
        [default_interface] runtimeclass LayoutMapManaged {
            LayoutMapManaged();
            String GetKeyName(UInt32 key);
            UInt32 GetKeyValue(String name);
            void Updatelayout();
        }
    }
}