//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FancyZonesEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FancyZonesEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new zone.
        /// </summary>
        public static string Add_zone {
            get {
                return ResourceManager.GetString("Add_zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply layout.
        /// </summary>
        public static string Apply_Layout {
            get {
                return ResourceManager.GetString("Apply_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string Are_You_Sure {
            get {
                return ResourceManager.GetString("Are_You_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this layout?.
        /// </summary>
        public static string Are_You_Sure_Description {
            get {
                return ResourceManager.GetString("Are_You_Sure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas layout editor.
        /// </summary>
        public static string Canvas_Layout_Editor {
            get {
                return ResourceManager.GetString("Canvas_Layout_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the layout for this desktop.
        /// </summary>
        public static string Choose_Layout {
            get {
                return ResourceManager.GetString("Choose_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose layout type.
        /// </summary>
        public static string Choose_layout_type {
            get {
                return ResourceManager.GetString("Choose_layout_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please report the bug to .
        /// </summary>
        public static string Crash_Report_Message_Box_Text {
            get {
                return ResourceManager.GetString("Crash_Report_Message_Box_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create custom layout.
        /// </summary>
        public static string Create_Custom_From_Template {
            get {
                return ResourceManager.GetString("Create_Custom_From_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new layout.
        /// </summary>
        public static string Create_new_layout {
            get {
                return ResourceManager.GetString("Create_new_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom layout.
        /// </summary>
        public static string Custom_Layout_Create_New {
            get {
                return ResourceManager.GetString("Custom_Layout_Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom layout creator.
        /// </summary>
        public static string Custom_Layout_Creator {
            get {
                return ResourceManager.GetString("Custom_Layout_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} slider. Possible range is from {1} to {2}. Value is {3}..
        /// </summary>
        public static string Custom_slider_announce {
            get {
                return ResourceManager.GetString("Custom_slider_announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom layout.
        /// </summary>
        public static string Default_Custom_Layout_Name {
            get {
                return ResourceManager.GetString("Default_Custom_Layout_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default layout for horizontal monitor orientation.
        /// </summary>
        public static string Default_Layout_Horizontal {
            get {
                return ResourceManager.GetString("Default_Layout_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default layout for vertical monitor orientation.
        /// </summary>
        public static string Default_Layout_Vertical {
            get {
                return ResourceManager.GetString("Default_Layout_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete layout dialog..
        /// </summary>
        public static string Delete_Layout_Dialog_Announce {
            get {
                return ResourceManager.GetString("Delete_Layout_Dialog_Announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete zone.
        /// </summary>
        public static string Delete_Zone {
            get {
                return ResourceManager.GetString("Delete_Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string Dimensions {
            get {
                return ResourceManager.GetString("Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight distance.
        /// </summary>
        public static string Distance_adjacent_zones {
            get {
                return ResourceManager.GetString("Distance_adjacent_zones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opened.
        /// </summary>
        public static string Edit_Layout_Open_Announce {
            get {
                return ResourceManager.GetString("Edit_Layout_Open_Announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit &apos;{0}&apos;.
        /// </summary>
        public static string Edit_Template {
            get {
                return ResourceManager.GetString("Edit_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit zones.
        /// </summary>
        public static string Edit_zones {
            get {
                return ResourceManager.GetString("Edit_zones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error applying layout.
        /// </summary>
        public static string Error_Applying_Layout {
            get {
                return ResourceManager.GetString("Error_Applying_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FancyZones Editor Exception Handler.
        /// </summary>
        public static string Error_Exception_Message_Box_Title {
            get {
                return ResourceManager.GetString("Error_Exception_Message_Box_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FancyZones Editor arguments are invalid..
        /// </summary>
        public static string Error_Invalid_Arguments {
            get {
                return ResourceManager.GetString("Error_Invalid_Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout &apos;{0}&apos; has malformed data.
        /// </summary>
        public static string Error_Layout_Malformed_Data {
            get {
                return ResourceManager.GetString("Error_Layout_Malformed_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading custom layouts.
        /// </summary>
        public static string Error_Loading_Custom_Layouts {
            get {
                return ResourceManager.GetString("Error_Loading_Custom_Layouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FancyZones Editor Error.
        /// </summary>
        public static string Error_Message_Box_Title {
            get {
                return ResourceManager.GetString("Error_Message_Box_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match not found ({0}).
        /// </summary>
        public static string Error_Monitor_Match_Not_Found {
            get {
                return ResourceManager.GetString("Error_Monitor_Match_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FancyZones Editor should not be run as standalone application..
        /// </summary>
        public static string Error_Not_Standalone_App {
            get {
                return ResourceManager.GetString("Error_Not_Standalone_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing applied layouts..
        /// </summary>
        public static string Error_Parsing_Applied_Layouts_Message {
            get {
                return ResourceManager.GetString("Error_Parsing_Applied_Layouts_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing custom layouts..
        /// </summary>
        public static string Error_Parsing_Custom_Layouts_Message {
            get {
                return ResourceManager.GetString("Error_Parsing_Custom_Layouts_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor data parsing error..
        /// </summary>
        public static string Error_Parsing_Data_Title {
            get {
                return ResourceManager.GetString("Error_Parsing_Data_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing default layouts..
        /// </summary>
        public static string Error_Parsing_Default_Layouts_Message {
            get {
                return ResourceManager.GetString("Error_Parsing_Default_Layouts_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing device info data..
        /// </summary>
        public static string Error_Parsing_Device_Info {
            get {
                return ResourceManager.GetString("Error_Parsing_Device_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing editor parameters..
        /// </summary>
        public static string Error_Parsing_Editor_Parameters_Message {
            get {
                return ResourceManager.GetString("Error_Parsing_Editor_Parameters_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing layout hotkeys..
        /// </summary>
        public static string Error_Parsing_Layout_Hotkeys_Message {
            get {
                return ResourceManager.GetString("Error_Parsing_Layout_Hotkeys_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing template layouts..
        /// </summary>
        public static string Error_Parsing_Layout_Templates_Message {
            get {
                return ResourceManager.GetString("Error_Parsing_Layout_Templates_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error persisting custom layout.
        /// </summary>
        public static string Error_Persisting_Custom_Layout {
            get {
                return ResourceManager.GetString("Error_Persisting_Custom_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please report the bug to .
        /// </summary>
        public static string Error_Report {
            get {
                return ResourceManager.GetString("Error_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error serializing deleted layouts.
        /// </summary>
        public static string Error_Serializing_Deleted_Layouts {
            get {
                return ResourceManager.GetString("Error_Serializing_Deleted_Layouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FancyZones Editor.
        /// </summary>
        public static string Fancy_Zones_Editor_App_Title {
            get {
                return ResourceManager.GetString("Fancy_Zones_Editor_App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FancyZones main editor.
        /// </summary>
        public static string Fancy_Zones_Main_Editor {
            get {
                return ResourceManager.GetString("Fancy_Zones_Main_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid layout editor.
        /// </summary>
        public static string Grid_Layout_Editor {
            get {
                return ResourceManager.GetString("Grid_Layout_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height_Name {
            get {
                return ResourceManager.GetString("Height_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///• Shift+S to split currently focused zone.
        ///• Ctrl+Tab to focus zones/resizers.
        ///• Tab to cycle zones and resizers.
        ///• Delete to remove the focused resizer.
        ///• Arrows to move the focused resizer..
        /// </summary>
        public static string KeyboardControlsDescription {
            get {
                return ResourceManager.GetString("KeyboardControlsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///• Ctrl+Tab to switch focus between dialog and zones.
        ///• Shift+Arrows to resize the focused zone by 10px (5px per edge).
        ///• Ctrl+Shift+Arrows to resize the focused zone by 2px (1px per edge).
        ///• Arrows to move the focused zone by 10px.
        ///• Ctrl+Arrows to move the focused zone by 1px..
        /// </summary>
        public static string KeyboardControlsDescriptionCanvas {
            get {
                return ResourceManager.GetString("KeyboardControlsDescriptionCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard navigation:.
        /// </summary>
        public static string KeyboardControlsName {
            get {
                return ResourceManager.GetString("KeyboardControlsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create layouts that have overlapping zones.
        /// </summary>
        public static string Layout_Canvas_Description {
            get {
                return ResourceManager.GetString("Layout_Canvas_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas.
        /// </summary>
        public static string Layout_Canvas_Title {
            get {
                return ResourceManager.GetString("Layout_Canvas_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom layout was created successfully..
        /// </summary>
        public static string Layout_Creation_Announce {
            get {
                return ResourceManager.GetString("Layout_Creation_Announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create layouts that are horizontally or vertically stacked.
        /// </summary>
        public static string Layout_Grid_Description {
            get {
                return ResourceManager.GetString("Layout_Grid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string Layout_Grid_Title {
            get {
                return ResourceManager.GetString("Layout_Grid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge zones.
        /// </summary>
        public static string Merge_zones {
            get {
                return ResourceManager.GetString("Merge_zones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click and drag across zones..
        /// </summary>
        public static string MergeDescription {
            get {
                return ResourceManager.GetString("MergeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge/Delete:.
        /// </summary>
        public static string MergeName {
            get {
                return ResourceManager.GetString("MergeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        public static string Monitor {
            get {
                return ResourceManager.GetString("Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor {0}.
        /// </summary>
        public static string Monitor_Index {
            get {
                return ResourceManager.GetString("Monitor_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New zone added.
        /// </summary>
        public static string New_zone_added {
            get {
                return ResourceManager.GetString("New_zone_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create or duplicate a layout to get started.
        /// </summary>
        public static string No_Custom_Layouts_Message {
            get {
                return ResourceManager.GetString("No_Custom_Layouts_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of zones.
        /// </summary>
        public static string Number_of_zones {
            get {
                return ResourceManager.GetString("Number_of_zones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of zones.
        /// </summary>
        public static string NumberOfZones {
            get {
                return ResourceManager.GetString("NumberOfZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        public static string OpenSettings {
            get {
                return ResourceManager.GetString("OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pixels.
        /// </summary>
        public static string Pixel_Value {
            get {
                return ResourceManager.GetString("Pixel_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to px.
        /// </summary>
        public static string Pixels {
            get {
                return ResourceManager.GetString("Pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Quick_Key_None {
            get {
                return ResourceManager.GetString("Quick_Key_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Win + Ctrl + Alt + selected key to apply this layout.
        /// </summary>
        public static string QuickKey_Description {
            get {
                return ResourceManager.GetString("QuickKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout shortcut.
        /// </summary>
        public static string QuickKey_Title {
            get {
                return ResourceManager.GetString("QuickKey_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset layout.
        /// </summary>
        public static string Reset_Layout {
            get {
                return ResourceManager.GetString("Reset_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the arrow keys to resize, delete key to remove..
        /// </summary>
        public static string Resizer_Thumb_Announce {
            get {
                return ResourceManager.GetString("Resizer_Thumb_Announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; apply.
        /// </summary>
        public static string Save_Apply {
            get {
                return ResourceManager.GetString("Save_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling.
        /// </summary>
        public static string Scaling {
            get {
                return ResourceManager.GetString("Scaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set layout as a default for horizontal monitor orientation.
        /// </summary>
        public static string Set_Layout_As_Horizontal_Default {
            get {
                return ResourceManager.GetString("Set_Layout_As_Horizontal_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set layout as a default for vertical monitor orientation.
        /// </summary>
        public static string Set_Layout_As_Vertical_Default {
            get {
                return ResourceManager.GetString("Set_Layout_As_Vertical_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show space around zones.
        /// </summary>
        public static string Show_Space_Zones {
            get {
                return ResourceManager.GetString("Show_Space_Zones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space around zones.
        /// </summary>
        public static string Space_Around_Zones {
            get {
                return ResourceManager.GetString("Space_Around_Zones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Shift key for vertical split..
        /// </summary>
        public static string SplitterDescription {
            get {
                return ResourceManager.GetString("SplitterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitter:.
        /// </summary>
        public static string SplitterName {
            get {
                return ResourceManager.GetString("SplitterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No layout.
        /// </summary>
        public static string Template_Layout_Blank {
            get {
                return ResourceManager.GetString("Template_Layout_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string Template_Layout_Columns {
            get {
                return ResourceManager.GetString("Template_Layout_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus.
        /// </summary>
        public static string Template_Layout_Focus {
            get {
                return ResourceManager.GetString("Template_Layout_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string Template_Layout_Grid {
            get {
                return ResourceManager.GetString("Template_Layout_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority Grid.
        /// </summary>
        public static string Template_Layout_Priority_Grid {
            get {
                return ResourceManager.GetString("Template_Layout_Priority_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        public static string Template_Layout_Rows {
            get {
                return ResourceManager.GetString("Template_Layout_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} zones.
        /// </summary>
        public static string Template_Zone_Count_Value {
            get {
                return ResourceManager.GetString("Template_Zone_Count_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width_Name {
            get {
                return ResourceManager.GetString("Width_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrement number of zones.
        /// </summary>
        public static string Zone_Count_Decrement {
            get {
                return ResourceManager.GetString("Zone_Count_Decrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment number of zones.
        /// </summary>
        public static string Zone_Count_Increment {
            get {
                return ResourceManager.GetString("Zone_Count_Increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string Zone_Name {
            get {
                return ResourceManager.GetString("Zone_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zones.
        /// </summary>
        public static string Zones {
            get {
                return ResourceManager.GetString("Zones", resourceCulture);
            }
        }
    }
}
