//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CmdPal.Ext.Bookmarks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CmdPal.Ext.Bookmarks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add bookmark.
        /// </summary>
        public static string bookmarks_add_name {
            get {
                return ResourceManager.GetString("bookmarks_add_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a bookmark.
        /// </summary>
        public static string bookmarks_add_title {
            get {
                return ResourceManager.GetString("bookmarks_add_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string bookmarks_delete_name {
            get {
                return ResourceManager.GetString("bookmarks_delete_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete bookmark.
        /// </summary>
        public static string bookmarks_delete_title {
            get {
                return ResourceManager.GetString("bookmarks_delete_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string bookmarks_display_name {
            get {
                return ResourceManager.GetString("bookmarks_display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit bookmark.
        /// </summary>
        public static string bookmarks_edit_name {
            get {
                return ResourceManager.GetString("bookmarks_edit_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL or file path.
        /// </summary>
        public static string bookmarks_form_bookmark_label {
            get {
                return ResourceManager.GetString("bookmarks_form_bookmark_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL or file path is required.
        /// </summary>
        public static string bookmarks_form_bookmark_required {
            get {
                return ResourceManager.GetString("bookmarks_form_bookmark_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark Type.
        /// </summary>
        public static string bookmarks_form_bookmark_type {
            get {
                return ResourceManager.GetString("bookmarks_form_bookmark_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Prompt.
        /// </summary>
        public static string bookmarks_form_bookmark_type_CMD {
            get {
                return ResourceManager.GetString("bookmarks_form_bookmark_type_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string bookmarks_form_bookmark_type_File {
            get {
                return ResourceManager.GetString("bookmarks_form_bookmark_type_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string bookmarks_form_bookmark_type_Folder {
            get {
                return ResourceManager.GetString("bookmarks_form_bookmark_type_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell.
        /// </summary>
        public static string bookmarks_form_bookmark_type_PowerShell {
            get {
                return ResourceManager.GetString("bookmarks_form_bookmark_type_PowerShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWSH.
        /// </summary>
        public static string bookmarks_form_bookmark_type_PWSH {
            get {
                return ResourceManager.GetString("bookmarks_form_bookmark_type_PWSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python.
        /// </summary>
        public static string bookmarks_form_bookmark_type_Python {
            get {
                return ResourceManager.GetString("bookmarks_form_bookmark_type_Python", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python3.
        /// </summary>
        public static string bookmarks_form_bookmark_type_Python3 {
            get {
                return ResourceManager.GetString("bookmarks_form_bookmark_type_Python3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string bookmarks_form_bookmark_type_web {
            get {
                return ResourceManager.GetString("bookmarks_form_bookmark_type_web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark type is required..
        /// </summary>
        public static string bookmarks_form_bookmarkType_required {
            get {
                return ResourceManager.GetString("bookmarks_form_bookmarkType_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string bookmarks_form_name_label {
            get {
                return ResourceManager.GetString("bookmarks_form_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string bookmarks_form_name_required {
            get {
                return ResourceManager.GetString("bookmarks_form_name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string bookmarks_form_open {
            get {
                return ResourceManager.GetString("bookmarks_form_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string bookmarks_form_save {
            get {
                return ResourceManager.GetString("bookmarks_form_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Terminal.
        /// </summary>
        public static string bookmarks_open_in_terminal_name {
            get {
                return ResourceManager.GetString("bookmarks_open_in_terminal_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string bookmarks_required_placeholder {
            get {
                return ResourceManager.GetString("bookmarks_required_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep the terminal window open.
        /// </summary>
        public static string bookmarks_settings_keepTerminalWindowOpen {
            get {
                return ResourceManager.GetString("bookmarks_settings_keepTerminalWindowOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not exit after running commands..
        /// </summary>
        public static string bookmarks_settings_keepTerminalWindowOpen_descrption {
            get {
                return ResourceManager.GetString("bookmarks_settings_keepTerminalWindowOpen_descrption", resourceCulture);
            }
        }
    }
}
