<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\Common.Dotnet.CsWinRT.props" />

  <PropertyGroup>
    <AssemblyName>PowerToys.AdvancedPaste.Core</AssemblyName>
    <RootNamespace>AdvancedPaste.Core</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="ReverseMarkdown" />
  </ItemGroup>
</Project>
