namespace PowerRenameUI
{
    [bindable] [default_interface] runtimeclass ExplorerItemViewModel :
        Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ExplorerItemViewModel();

        Int32 IdVM { get; };
        String IdStrVM { get; };
        String OriginalVM { get; };
        String RenamedVM { get; };
        Double IndentationVM { get; };
        String ImagePathVM { get; };
        Int32 TypeVM { get; };
        Boolean CheckedVM;
        Int32 StateVM { get; };
    }
}
