namespace PowerRenameUI
{
    [default_interface] runtimeclass ExplorerItem : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ExplorerItem();
        ExplorerItem(Int32 id, String original, String renamed, Int32 type, UInt32 depth, Boolean checked);
        
        Int32 Id;
        String IdStr;
        String Original;
        String Renamed;
        Double Indentation;
        String ImagePath;
        Int32 Type;
        Boolean Checked;
        Int32 State;
        
        static Microsoft.UI.Xaml.DependencyProperty CheckedProperty { get; };
    }
}
