// IVectorView and IObservableVector define members with the same name, and we must support both interfaces
midl_pragma warning(disable : 4066)

namespace PowerRenameUI
{
    [default_interface] runtimeclass ExplorerItemsSource : 
        Microsoft.UI.Xaml.Data.IItemsRangeInfo, 
        Microsoft.UI.Xaml.Data.ISelectionInfo,
        Windows.Foundation.Collections.IVectorView<IInspectable>,
        Windows.Foundation.Collections.IObservableVector<IInspectable>,
        Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ExplorerItemsSource();
    }
}
