namespace PowerRenameUI
{
    [default_interface] runtimeclass ExplorerItem : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ExplorerItem();
        ExplorerItem(Int32 id, String original, String renamed, Int32 type, UInt32 depth, Boolean checked);
        Int32 Id { get; };
        String IdStr { get; };
        String Original;
        String Renamed;
        Double Indentation { get; };
        String ImagePath { get; };
        Int32 Type;
        Boolean Checked;
        Int32 State;
    }
}
