namespace PowerRenameUILib
{
    [bindable]
        [default_interface] runtimeclass ExplorerItemTemplateSelector : Windows.UI.Xaml.Controls.DataTemplateSelector
    {
        ExplorerItemTemplateSelector();

        Windows.UI.Xaml.DataTemplate FolderTemplate;
        Windows.UI.Xaml.DataTemplate FileTemplate;
    }
}
