import "ExplorerItem.idl";
import "PatternSnippet.idl";
import "UIUpdates.idl";

namespace PowerRenameUI
{
    [default_interface] runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();

        Windows.Foundation.Collections.IObservableVector<String> SearchMRU { get; };
        Windows.Foundation.Collections.IObservableVector<String> ReplaceMRU { get; };

        Windows.Foundation.Collections.IObservableVector<ExplorerItem> ExplorerItems { get; };
        Windows.Foundation.Collections.IObservableVector<PatternSnippet> SearchRegExShortcuts { get; };
        Windows.Foundation.Collections.IObservableVector<PatternSnippet> DateTimeShortcuts { get; };

        UIUpdates UIUpdatesItem { get; };

        void AddExplorerItem(Int32 id, String original, String renamed, Int32 type, UInt32 depth, Boolean checked);
        void UpdateExplorerItem(Int32 id, String newName);
        void UpdateRenamedExplorerItem(Int32 id, String newOriginalName);
        void AppendSearchMRU(String value);
        void AppendReplaceMRU(String value);

    }
}
