import "ExplorerItem.idl";
import "PatternSnippet.idl";

namespace PowerRenameUI
{
    [default_interface] runtimeclass MainWindow : Microsoft.UI.Xaml.Window, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        MainWindow();

        Windows.Foundation.Collections.IObservableVector<String> SearchMRU { get; };
        Windows.Foundation.Collections.IObservableVector<String> ReplaceMRU { get; };

        Windows.Foundation.Collections.IObservableVector<ExplorerItem> ExplorerItems { get; };
        Windows.Foundation.Collections.IObservableVector<PatternSnippet> SearchRegExShortcuts { get; };
        Windows.Foundation.Collections.IObservableVector<PatternSnippet> DateTimeShortcuts { get; };

        String OriginalCount;
        String RenamedCount;

        void AddExplorerItem(Int32 id, String original, String renamed, Int32 type, UInt32 depth, Boolean checked);
        void UpdateExplorerItem(Int32 id, String newName);
        void UpdateRenamedExplorerItem(Int32 id, String newOriginalName);
    }
}
