namespace PowerRenameUI
{
    runtimeclass UIUpdates : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UIUpdates();
        Boolean ShowAll;
        Boolean CloseUIWindow();
        void CloseUIWindow(Boolean closeUIWindow);
        Boolean ButtonRenameEnabled;
        void Rename();
        String OriginalCount;
        String RenamedCount;
    }
}
