// Copyright (c) Microsoft Corporation
// The Microsoft Corporation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

// <auto-generated/>
#nullable enable

using System.Drawing;
using System.Runtime.InteropServices;

using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.Graphics.Gdi;
using Windows.Win32.UI.HiDpi;
using Windows.Win32.UI.Input.KeyboardAndMouse;
using Windows.Win32.UI.Shell;
using Windows.Win32.UI.WindowsAndMessaging;

namespace MouseJump.Common.Win32Gen;

internal static partial class User32
{
    /// <summary>Displays a shortcut menu at the specified location and tracks the selection of items on the shortcut menu. The shortcut menu can appear anywhere on the screen.</summary>
    /// <param name="hMenu">
    /// <para>Type: <b>HMENU</b> A handle to the shortcut menu to be displayed. This handle can be obtained by calling the <a href="https://docs.microsoft.com/windows/desktop/api/winuser/nf-winuser-createpopupmenu">CreatePopupMenu</a> function to create a new shortcut menu or by calling the <a href="https://docs.microsoft.com/windows/desktop/api/winuser/nf-winuser-getsubmenu">GetSubMenu</a> function to retrieve a handle to a submenu associated with an existing menu item.</para>
    /// <para><see href="https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-trackpopupmenuex#parameters">Read more on learn.microsoft.com</see>.</para>
    /// </param>
    /// <param name="uFlags">
    /// <para>Type: <b>UINT</b> Specifies function options.</para>
    /// <para>Use one of the following flags to specify how the function positions the shortcut menu horizontally.</para>
    /// <para></para>
    /// <para>This doc was truncated.</para>
    /// <para><see href="https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-trackpopupmenuex#parameters">Read more on learn.microsoft.com</see>.</para>
    /// </param>
    /// <param name="x">
    /// <para>Type: <b>int</b> The horizontal location of the shortcut menu, in screen coordinates.</para>
    /// <para><see href="https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-trackpopupmenuex#parameters">Read more on learn.microsoft.com</see>.</para>
    /// </param>
    /// <param name="y">
    /// <para>Type: <b>int</b> The vertical location of the shortcut menu, in screen coordinates.</para>
    /// <para><see href="https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-trackpopupmenuex#parameters">Read more on learn.microsoft.com</see>.</para>
    /// </param>
    /// <param name="hwnd">
    /// <para>Type: <b>HWND</b> A handle to the window that owns the shortcut menu. This window receives all messages from the menu. The window does not receive a <a href="https://docs.microsoft.com/windows/desktop/menurc/wm-command">WM_COMMAND</a> message from the menu until the function returns. If you specify TPM_NONOTIFY in the <i>fuFlags</i> parameter, the function does not send messages to the window identified by <i>hwnd</i>. However, you must still pass a window handle in <i>hwnd</i>. It can be any window handle from your application.</para>
    /// <para><see href="https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-trackpopupmenuex#parameters">Read more on learn.microsoft.com</see>.</para>
    /// </param>
    /// <param name="lptpm">
    /// <para>Type: <b>LPTPMPARAMS</b> A pointer to a <a href="https://docs.microsoft.com/windows/desktop/api/winuser/ns-winuser-tpmparams">TPMPARAMS</a> structure that specifies an area of the screen the menu should not overlap. This parameter can be <b>NULL</b>.</para>
    /// <para><see href="https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-trackpopupmenuex#parameters">Read more on learn.microsoft.com</see>.</para>
    /// </param>
    /// <returns>
    /// <para>Type: <b>BOOL</b> If you specify <b>TPM_RETURNCMD</b> in the <i>fuFlags</i> parameter, the return value is the menu-item identifier of the item that the user selected. If the user cancels the menu without making a selection, or if an error occurs, the return value is zero. If you do not specify <b>TPM_RETURNCMD</b> in the <i>fuFlags</i> parameter, the return value is nonzero if the function succeeds and zero if it fails. To get extended error information, call <a href="https://docs.microsoft.com/windows/desktop/api/errhandlingapi/nf-errhandlingapi-getlasterror">GetLastError</a>.</para>
    /// </returns>
    /// <remarks>
    /// <para>Call <a href="https://docs.microsoft.com/windows/desktop/api/winuser/nf-winuser-getsystemmetrics">GetSystemMetrics</a> with <b>SM_MENUDROPALIGNMENT</b> to determine the correct horizontal alignment flag (<b>TPM_LEFTALIGN</b> or <b>TPM_RIGHTALIGN</b>) and/or horizontal animation direction flag (<b>TPM_HORPOSANIMATION</b> or <b>TPM_HORNEGANIMATION</b>) to pass to <a href="https://docs.microsoft.com/windows/desktop/api/winuser/nf-winuser-trackpopupmenu">TrackPopupMenu</a> or <b>TrackPopupMenuEx</b>. This is essential for creating an optimal user experience, especially when developing Microsoft Tablet PC applications. To display a context menu for a notification icon, the current window must be the foreground window before the application calls <a href="https://docs.microsoft.com/windows/desktop/api/winuser/nf-winuser-trackpopupmenu">TrackPopupMenu</a> or <b>TrackPopupMenuEx</b>. Otherwise, the menu will not disappear when the user clicks outside of the menu or the window that created the menu (if it is visible). If the current window is a child window, you must set the (top-level) parent window as the foreground window.</para>
    /// <para><see href="https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-trackpopupmenuex#">Read more on learn.microsoft.com</see>.</para>
    /// </remarks>
    internal static Win32Result<BOOL> TrackPopupMenuEx(SafeHandle hMenu, uint uFlags, int x, int y, HWND hwnd, TPMPARAMS? lptpm)
    {
        // https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-trackpopupmenuex
        // If you specify TPM_RETURNCMD in the fuFlags parameter, the return value is the menu-item identifier of the item that the user selected.
        // If the user cancels the menu without making a selection, or if an error occurs, the return value is zero.
        // If you do not specify TPM_RETURNCMD in the fuFlags parameter, the return value is nonzero if the function succeeds and zero if it fails.
        // To get extended error information, call GetLastError.
        var result = PInvoke.TrackPopupMenuEx(hMenu, uFlags, x, y, hwnd, lptpm)
            .SuccessIsNonZero();

        // With TPM_RETURNCMD set, a zero result means either "the user cancelled"
        // or "an error occurred" - the docs don't say GetLastError can tell those
        // apart, so it isn't captured here, to avoid reporting a stale or
        // misleading error code for what may just be a cancelled selection.
        if ((uFlags & (uint)TRACK_POPUP_MENU_FLAGS.TPM_RETURNCMD) == 0)
        {
            result = result.WithLastError();
        }

        return result;
    }
}
