// Copyright (c) Microsoft Corporation
// The Microsoft Corporation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

// <auto-generated/>
#nullable enable

using System.Drawing;
using System.Runtime.InteropServices;

using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.Graphics.Gdi;
using Windows.Win32.UI.HiDpi;
using Windows.Win32.UI.Input.KeyboardAndMouse;
using Windows.Win32.UI.Shell;
using Windows.Win32.UI.WindowsAndMessaging;

namespace MouseJump.Common.Win32Gen;

internal static partial class User32
{
    /// <summary>The MonitorFromPoint function retrieves a handle to the display monitor that contains a specified point.</summary>
    /// <param name="pt">A <a href="https://docs.microsoft.com/windows/win32/api/windef/ns-windef-point">POINT</a> structure that specifies the point of interest in virtual-screen coordinates.</param>
    /// <param name="dwFlags">Determines the function's return value if the point is not contained within any display monitor.</param>
    /// <returns>
    /// <para>If the point is contained by a display monitor, the return value is an <b>HMONITOR</b> handle to that display monitor. If the point is not contained by a display monitor, the return value depends on the value of <i>dwFlags</i>.</para>
    /// </returns>
    /// <remarks>
    /// <para><see href="https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-monitorfrompoint">Learn more about this API from learn.microsoft.com</see>.</para>
    /// </remarks>
    internal static Win32Result<HMONITOR> MonitorFromPoint(Point pt, MONITOR_FROM_FLAGS dwFlags)
    {
        // https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-monitorfrompoint
        // If the point is contained by a display monitor, the return value is an HMONITOR handle to that display monitor.
        // If the point is not contained by a display monitor, the return value depends on the value of dwFlags.
        return PInvoke.MonitorFromPoint(pt, dwFlags)
            .SuccessIsNotNull();
    }
}
