// Copyright (c) Microsoft Corporation
// The Microsoft Corporation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

// <auto-generated/>
#nullable enable

using System.Drawing;
using System.Runtime.InteropServices;

using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.Graphics.Gdi;
using Windows.Win32.UI.HiDpi;
using Windows.Win32.UI.Input.KeyboardAndMouse;
using Windows.Win32.UI.Shell;
using Windows.Win32.UI.WindowsAndMessaging;

namespace MouseJump.Common.Win32Gen;

internal static partial class User32
{
    /// <summary>Retrieves the specified system metric or system configuration setting.</summary>
    /// <param name="nIndex">Type: <b>int</b></param>
    /// <returns>
    /// <para>Type: <b>int</b> If the function succeeds, the return value is the requested system metric or configuration setting. If the function fails, the return value is 0. <a href="https://docs.microsoft.com/windows/desktop/api/errhandlingapi/nf-errhandlingapi-getlasterror">GetLastError</a> does not provide extended error information.</para>
    /// </returns>
    /// <remarks>
    /// <para>System metrics can vary from display to display. <b>GetSystemMetrics</b>(SM_CMONITORS) counts only visible display monitors. This is different from <a href="https://docs.microsoft.com/windows/desktop/api/winuser/nf-winuser-enumdisplaymonitors">EnumDisplayMonitors</a>, which enumerates both visible display monitors and invisible  pseudo-monitors that are associated with mirroring drivers. An invisible pseudo-monitor is associated with a pseudo-device used to mirror application drawing for remoting or other purposes. The SM_ARRANGE setting specifies how the system arranges minimized windows, and consists of a starting position and a direction. The starting position can be one of the following values.</para>
    /// <para></para>
    /// <para>This doc was truncated.</para>
    /// <para><see href="https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-getsystemmetrics#">Read more on learn.microsoft.com</see>.</para>
    /// </remarks>
    internal static Win32Result<int> GetSystemMetrics(SYSTEM_METRICS_INDEX nIndex)
    {
        // https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetrics
        // If the function succeeds, the return value is the requested system metric or configuration setting.
        // If the function fails, the return value is 0.
        // GetLastError does not provide extended error information, so it isn't
        // captured here even though 0 is treated as failure.
        return PInvoke.GetSystemMetrics(nIndex)
            .SuccessIsNonZero();
    }
}
