// Copyright (c) Microsoft Corporation
// The Microsoft Corporation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

// <auto-generated/>
#nullable enable

using System.Drawing;
using System.Runtime.InteropServices;

using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.Graphics.Gdi;
using Windows.Win32.UI.HiDpi;
using Windows.Win32.UI.Input.KeyboardAndMouse;
using Windows.Win32.UI.Shell;
using Windows.Win32.UI.WindowsAndMessaging;

namespace MouseJump.Common.Win32Gen;

internal static partial class User32
{
    /// <summary>Retrieves the DPI_AWARENESS value from a DPI_AWARENESS_CONTEXT.</summary>
    /// <param name="value">The <b>DPI_AWARENESS_CONTEXT</b> you want to examine.</param>
    /// <returns>The <a href="https://docs.microsoft.com/windows/desktop/api/windef/ne-windef-dpi_awareness">DPI_AWARENESS</a>. If the provided <i>value</i> is <b>null</b> or invalid, this method will return <b>DPI_AWARENESS_INVALID</b>.</returns>
    /// <remarks>A <a href="https://docs.microsoft.com/windows/desktop/hidpi/dpi-awareness-context">DPI_AWARENESS_CONTEXT</a> contains multiple pieces of information. For example, it includes both the current and the inherited <a href="https://docs.microsoft.com/windows/desktop/api/windef/ne-windef-dpi_awareness">DPI_AWARENESS</a>. This method retrieves the <b>DPI_AWARENESS</b> from the structure.</remarks>
    internal static Win32Result<DPI_AWARENESS> GetAwarenessFromDpiAwarenessContext(DPI_AWARENESS_CONTEXT value)
    {
        // https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getawarenessfromdpiawarenesscontext
        // If the provided value is null or invalid, this method will return DPI_AWARENESS_INVALID.
        var result = PInvoke.GetAwarenessFromDpiAwarenessContext(value);
        var success = result != DPI_AWARENESS.DPI_AWARENESS_INVALID;
        return new Win32Result<DPI_AWARENESS>(result, success);
    }
}
