// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.UI
{
    static runtimeclass IconPathConverter
    {
        // static Windows.UI.Xaml.Controls.IconElement IconWUX(String path);
        // static Windows.UI.Xaml.Controls.IconSource IconSourceWUX(String path);
        static Microsoft.UI.Xaml.Controls.IconSource IconSourceMUX(String path, Boolean convertToGrayscale);
        static Microsoft.UI.Xaml.Controls.IconElement IconMUX(String path);
        static Microsoft.UI.Xaml.Controls.IconElement IconMUX(String path, Int32 targetSize);
    };

}
