// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.UI
{
    [uuid("0ddf4edc-3fda-4dee-97ca-a417ee3dd510")]
    interface IDirectKeyListener {
        Boolean OnDirectKeyEvent(UInt32 vkey, UInt8 scanCode, Boolean down);
    }
}
