// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.UI
{
    static runtimeclass RunHistory
    {
        static Windows.Foundation.Collections.IVector<String> CreateRunHistory();
    };

}
