// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.UI
{
    struct TasklistButton
    {
        String Name;
        Int32 X;
        Int32 Y;
        Int32 Width;
        Int32 Height;
        Int32 KeyNum;
    };

    static runtimeclass Tasklist
    {
        static Windows.Foundation.Collections.IVector<TasklistButton> GetButtons();
    };
}
